Repository trixi-framework/Trixi.jl, pull requests merged in 2021-08, with the labels that each got.

#768 improve performance of MHD (quite a bit) and Euler (a little bit)
  src/equations/compressible_euler_1d.jl
  src/equations/compressible_euler_2d.jl
  src/equations/compressible_euler_3d.jl
  src/equations/ideal_glm_mhd_1d.jl
  src/equations/ideal_glm_mhd_2d.jl
  src/equations/ideal_glm_mhd_3d.jl
  test/test_examples_1d_euler.jl
  test/test_examples_2d_p4est.jl
  test/test_examples_3d_structured.jl
Labels: performance

#767 p4est interface performance
  benchmark/benchmarks.jl
  benchmark/elixir_2d_euler_vortex_p4est.jl
  examples/p4est_2d_dgsem/elixir_advection_nonconforming_unstructured.jl
  src/solvers/dgsem_p4est/containers.jl
  src/solvers/dgsem_p4est/dg.jl
  src/solvers/dgsem_p4est/dg_2d.jl
Labels: performance

#778 P4estMesh: workaround for type instability in prolong2mortars
  src/Trixi.jl
Labels: performance, upstream

#776 faster `min` and `max`
  src/auxiliary/math.jl
Labels: performance

#783 p4est surface performance 3D
  examples/p4est_3d_dgsem/elixir_advection_cubed_sphere.jl
  examples/p4est_3d_dgsem/elixir_advection_nonconforming.jl
  examples/tree_3d_dgsem/elixir_advection_extended.jl
  src/solvers/dgsem_p4est/dg.jl
  src/solvers/dgsem_p4est/dg_2d.jl
  src/solvers/dgsem_p4est/dg_3d.jl
Labels: performance

#613 Makie visualization for general meshes
  Project.toml
  docs/src/visualization.md
  examples/dgmulti_2d/elixir_euler_triangulate_pkg_mesh.jl
  src/Trixi.jl
  src/callbacks_step/visualization.jl
  src/visualization/interpolate.jl
  src/visualization/makie_visualization.jl
  src/visualization/plot_recipes.jl
  test/Project.toml
  test/test_visualization.jl
Labels: visualization

#791 Add tutorial for HOHQMesh to Trixi docs
  docs/make.jl
  docs/src/hohqmesh_tutorial.md
Labels: documentation

#806 remove Trixi2Img from the docs
  docs/Project.toml
  docs/make.jl
  docs/src/development.md
  docs/src/reference-trixi2img.md
  docs/src/testing.md
  docs/src/visualization.md
Labels: breaking

#807 remove old nonconservative stuff
  docs/src/development.md
  src/equations/ideal_glm_mhd_2d.jl
  src/equations/ideal_glm_mhd_3d.jl
  src/equations/ideal_glm_mhd_multicomponent_2d.jl
  src/solvers/dgsem_structured/dg_2d.jl
  src/solvers/dgsem_structured/dg_3d.jl
  src/solvers/dgsem_tree/dg_1d.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_tree/dg_3d.jl
  src/solvers/dgsem_unstructured/dg_2d.jl
  test/test_examples_1d.jl
  test/test_examples_2d_mhd.jl
  test/test_examples_2d_mhdmulti.jl
  test/test_examples_2d_structured.jl
  test/test_examples_2d_unstructured.jl
  test/test_examples_3d_mhd.jl
  test/test_examples_3d_structured.jl
Labels: breaking

#781 DGMulti improvements and preparation for Gauss collocation solver
  examples/dgmulti_2d/elixir_euler_kelvin_helmholtz_instability.jl
  examples/dgmulti_2d/elixir_euler_rayleigh_taylor_instability.jl
  examples/dgmulti_2d/elixir_euler_weakform.jl
  src/callbacks_step/analysis_dgmulti.jl
  src/solvers/dgmulti.jl
  src/solvers/dgmulti/dg.jl
  src/solvers/dgmulti/flux_differencing.jl
  src/solvers/dgmulti/types.jl
  src/solvers/solvers.jl
  src/visualization/recipes_makie.jl
  src/visualization/utilities.jl
  test/test_examples_dgmulti.jl
Labels: enhancement

#822 improve performance of DGMulti methods using entropy-projections (for 2D Euler)
  src/solvers/dgmulti.jl
  src/solvers/dgmulti/dg.jl
  src/solvers/dgmulti/flux_differencing.jl
  src/solvers/dgmulti/flux_differencing_compressible_euler.jl
Labels: performance

#810 Conservative formulation of the acoustic perturbation equations
  NEWS.md
  examples/tree_2d_dgsem/elixir_ape_convergence.jl
  src/equations/acoustic_perturbation_2d.jl
  test/test_tree_2d_ape.jl
  test/test_unit.jl
Labels: breaking
