Repository trixi-framework/Trixi.jl, pull requests merged in 2021-11, with the labels that each got.

#957 Improve entropy projection for DGMulti with GSBP
  src/solvers/dgmulti/flux_differencing.jl
  src/solvers/dgmulti/flux_differencing_compressible_euler.jl
  src/solvers/dgmulti/flux_differencing_gsbp.jl
Labels: performance

#960 Fix introduction to DG methods
  docs/literate/src/files/scalar_linear_advection_1d.jl
Labels: documentation

#907 Added slicing for general meshes
  src/visualization/recipes_plots.jl
  src/visualization/types.jl
  src/visualization/utilities.jl
  test/test_visualization.jl
Labels: visualization

#945 P4estMesh constructor for HOHQMesh Abaqus-type file
  docs/src/meshes/p4est_mesh.md
  examples/p4est_2d_dgsem/elixir_euler_wall_bc_amr.jl
  examples/p4est_3d_dgsem/elixir_euler_source_terms_nonperiodic_hohqmesh.jl
  src/auxiliary/p4est.jl
  src/meshes/face_interpolant.jl
  src/meshes/mesh_io.jl
  src/meshes/meshes.jl
  src/meshes/p4est_mesh.jl
  src/meshes/transfinite_mappings_3d.jl
  src/meshes/unstructured_mesh.jl
  src/solvers/dgsem_p4est/containers.jl
  src/solvers/dgsem_p4est/containers_2d.jl
  src/solvers/dgsem_p4est/containers_3d.jl
  src/solvers/dgsem_p4est/dg.jl
  src/solvers/dgsem_unstructured/mappings_geometry_curved_2d.jl
  src/solvers/dgsem_unstructured/mappings_geometry_straight_2d.jl
  test/test_p4est_2d.jl
  test/test_p4est_3d.jl
  test/test_unstructured_2d.jl
Labels: enhancement, upstream

#942 Add an idealized baroclinic instability test and two accessory elixirs
  examples/p4est_3d_dgsem/elixir_euler_baroclinic_instability.jl
  examples/p4est_3d_dgsem/elixir_euler_circular_wind_nonconforming.jl
  examples/p4est_3d_dgsem/elixir_euler_source_terms_nonconforming_earth.jl
  src/Trixi.jl
  src/equations/compressible_euler_3d.jl
  test/test_p4est_3d.jl
  test/test_unit.jl
Labels: enhancement

#966 Use sparse `Pf` operators for `DGMulti` with `GaussSBP`
  src/solvers/dgmulti/dg.jl
  src/solvers/dgmulti/flux_differencing_compressible_euler.jl
  src/solvers/dgmulti/flux_differencing_gauss_sbp.jl
Labels: performance

#969 enable sparse `Qrst_skew` operators for flux differencing `DGMulti`
  src/Trixi.jl
  src/solvers/dgmulti/dg.jl
  src/solvers/dgmulti/flux_differencing.jl
  src/solvers/dgmulti/flux_differencing_gauss_sbp.jl
Labels: performance

#972 reduce CI times
  test/test_structured_2d.jl
  test/test_structured_3d.jl
  test/test_tree_3d_advection.jl
  test/test_tree_3d_euler.jl
  test/test_visualization.jl
Labels: testing

#973 make some coverage tests in p4est_part2 cheaper
  test/test_p4est_3d.jl
Labels: testing

#990 specialize 3D Cartesian `split_form_kernel!` on `flux_shima_etal`
  src/solvers/dgsem_tree/dg.jl
  src/solvers/dgsem_tree/dg_3d_compressible_euler.jl
  test/runtests.jl
  test/test_performance_specializations.jl
Labels: performance

#993 specialize 3D curved `split_form_kernel!` on `flux_shima_etal`
  src/solvers/dgsem_structured/dg.jl
  src/solvers/dgsem_structured/dg_3d_compressible_euler.jl
  test/test_performance_specializations.jl
Labels: performance

#996 do not test MPI on Windows with coverage
  test/runtests.jl
Labels: testing

#997 Improve performance of surface integral
  docs/literate/src/files/differentiable_programming.jl
  examples/p4est_3d_dgsem/elixir_euler_ec.jl
  src/equations/compressible_euler_2d.jl
  src/equations/compressible_euler_3d.jl
  src/equations/shallow_water_2d.jl
  src/solvers/dgsem_p4est/dg_2d.jl
  src/solvers/dgsem_p4est/dg_3d.jl
  src/solvers/dgsem_tree/dg_1d.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_tree/dg_3d.jl
  test/test_structured_2d.jl
  test/test_tree_1d_hypdiff.jl
  test/test_tree_2d_euler.jl
Labels: performance
