Repository trixi-framework/Trixi.jl, pull requests merged in 2022-02, with the labels that each got.

#1048 introduce keyword argument `skip_coverage` of `@test_trixi_include`
  test/runtests.jl
  test/test_trixi.jl
Labels: testing

#1061 Youtube badge
  README.md
  docs/src/index.md
Labels: documentation

#985 Check CI on Julia v1.7
  .github/workflows/Documenter.yml
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  NEWS.md
  Project.toml
  README.md
  docs/src/development.md
  docs/src/index.md
  examples/p4est_2d_dgsem/elixir_advection_extended.jl
  examples/structured_2d_dgsem/elixir_advection_extended.jl
  src/Trixi.jl
  test/test_p4est_2d.jl
  test/test_structured_2d.jl
  test/test_threaded.jl
  test/test_tree_2d_euler.jl
  test/test_trixi.jl
  test/test_visualization.jl
Labels: testing

#1044 Added 3D to 1D plotting along an axis/curve for general meshes
  src/Trixi.jl
  src/visualization/types.jl
  src/visualization/utilities.jl
  test/test_visualization.jl
Labels: visualization

#1068 Bug fix in div(B) computation
  src/callbacks_step/analysis_dg2d.jl
  src/callbacks_step/analysis_dg3d.jl
Labels: bug
