Repository trixi-framework/Trixi.jl, pull requests merged in 2022-11, with the labels that each got.

#1260 Correct typo in documentation
  src/visualization/types.jl
Labels: documentation

#1259 Fix colorbar `range_step` error for`iplot`
  src/visualization/recipes_makie.jl
  test/test_visualization.jl
Labels: visualization

#1266 document `PlotData*D(u, semi)`
  docs/src/visualization.md
Labels: documentation, visualization

#1272 update solution return code checking to enums
  Project.toml
  src/callbacks_step/euler_acoustics_coupling.jl
Labels: upstream

#1274 improve some docstrings
  src/solvers/dg.jl
  src/solvers/dgsem_tree/indicators.jl
Labels: documentation

#1280 fix `convergence_test` for elixirs without trailing new line
  src/auxiliary/special_elixirs.jl
Labels: bug
