Repository trixi-framework/Trixi.jl, pull requests merged in 2022-10, with the labels that each got.

#1224 fix parabolic PID
  examples/tree_2d_dgsem/elixir_navier_stokes_convergence.jl
  src/auxiliary/auxiliary.jl
  src/semidiscretization/semidiscretization_hyperbolic_parabolic.jl
Labels: bug

#1149 Incorporate parabolic terms into `main`
  .github/workflows/ci.yml
  NEWS.md
  docs/literate/src/files/adding_new_parabolic_terms.jl
  docs/literate/src/files/parabolic_terms.jl
  docs/make.jl
  examples/dgmulti_2d/elixir_advection_diffusion.jl
  examples/dgmulti_2d/elixir_advection_diffusion_nonperiodic.jl
  examples/dgmulti_2d/elixir_advection_diffusion_periodic.jl
  examples/dgmulti_2d/elixir_navierstokes_convergence.jl
  examples/dgmulti_2d/elixir_navierstokes_lid_driven_cavity.jl
  examples/tree_2d_dgsem/elixir_advection_diffusion.jl
  examples/tree_2d_dgsem/elixir_advection_diffusion_nonperiodic.jl
  examples/tree_2d_dgsem/elixir_navierstokes_convergence.jl
  examples/tree_2d_dgsem/elixir_navierstokes_lid_driven_cavity.jl
  src/Trixi.jl
  src/auxiliary/auxiliary.jl
  src/basic_types.jl
  src/equations/compressible_euler_1d.jl
  src/equations/compressible_euler_2d.jl
  src/equations/compressible_euler_3d.jl
  src/equations/compressible_euler_multicomponent_1d.jl
  src/equations/compressible_euler_multicomponent_2d.jl
  src/equations/compressible_navier_stokes_2d.jl
  src/equations/equations.jl
  src/equations/equations_parabolic.jl
  src/equations/laplace_diffusion_2d.jl
  src/semidiscretization/semidiscretization_hyperbolic_parabolic.jl
  src/solvers/dgmulti.jl
  src/solvers/dgmulti/dg.jl
  src/solvers/dgmulti/dg_parabolic.jl
  src/solvers/dgmulti/sbp.jl
  src/solvers/dgsem_p4est/dg_2d.jl
  src/solvers/dgsem_p4est/dg_3d.jl
  src/solvers/dgsem_tree/dg.jl
  src/solvers/dgsem_tree/dg_1d.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_tree/dg_2d_parabolic.jl
  src/solvers/dgsem_tree/dg_3d.jl
  src/solvers/dgsem_unstructured/dg_2d.jl
  src/solvers/solvers.jl
  src/solvers/solvers_parabolic.jl
  test/runtests.jl
  test/test_dgmulti_2d.jl
  test/test_parabolic_2d.jl
Labels: enhancement

#1232 bump compat for MPI to 0.20
  Project.toml
  src/callbacks_step/amr_dg.jl
  src/callbacks_step/amr_dg2d.jl
  src/solvers/dgsem_p4est/dg_parallel.jl
  src/solvers/dgsem_tree/dg_2d_parallel.jl
  test/Project.toml
Labels: upstream
