Repository trixi-framework/Trixi.jl, pull requests merged in 2023-03, with the labels that each got.

#1372 follow SciMLBase update destats -> stats
  .github/workflows/Documenter.yml
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  NEWS.md
  Project.toml
  README.md
  docs/Project.toml
  docs/src/development.md
  docs/src/index.md
  src/callbacks_step/alive.jl
  src/callbacks_step/amr.jl
  src/callbacks_step/analysis.jl
  src/callbacks_step/save_restart.jl
  src/callbacks_step/save_solution.jl
  src/callbacks_step/time_series.jl
  src/callbacks_step/visualization.jl
  src/time_integration/methods_2N.jl
  src/time_integration/methods_3Sstar.jl
  test/Project.toml
  test/test_performance_specializations.jl
Labels: upstream

#1366 Fix that rank with no element gets stuck
  src/callbacks_step/save_restart_dg.jl
Labels: parallelization

#1376 switch to SimpleUnPack.jl
  NEWS.md
  Project.toml
  examples/structured_1d_dgsem/elixir_advection_shockcapturing.jl
  src/Trixi.jl
  src/solvers/dgsem_tree/indicators_1d.jl
  test/test_structured_1d.jl
Labels: upstream

#1377 Correct LaTex Syntax for Linearized Euler Eqs
  src/equations/linearized_euler_2d.jl
Labels: documentation
