Repository trixi-framework/Trixi.jl, pull requests merged in 2023-09, with the labels that each got.

#1613 Update docs on how to use a system-provided MPI installation with T8code.jl
  docs/src/parallelization.md
Labels: documentation

#1504 Update docs for parallel HDF5
  Project.toml
  docs/src/parallelization.md
Labels: documentation

#1630 Some multi-threading improvements
  src/solvers/dgmulti/dg_parabolic.jl
  src/solvers/dgsem_tree/dg_1d_parabolic.jl
  src/solvers/dgsem_tree/dg_2d_parabolic.jl
  src/solvers/dgsem_tree/dg_3d_parabolic.jl
Labels: bug, parallelization

#1634 Shorten 3d parabolic test times
  test/test_parabolic_3d.jl
Labels: testing

#1636 fix allocations of P4estMesh2D BCs
  src/solvers/dgsem_p4est/dg_2d.jl
  test/test_p4est_2d.jl
Labels: performance

#1637 Avoid slicing in BCs since it leads to allocations
  examples/p4est_2d_dgsem/elixir_navierstokes_convergence.jl
  examples/p4est_3d_dgsem/elixir_navierstokes_convergence.jl
Labels: performance

#1633 new tutorial on custom RHS functions and semidiscretizations
  docs/literate/make.jl
  docs/literate/src/files/custom_semidiscretization.jl
  docs/literate/src/files/index.jl
  docs/make.jl
  docs/src/callbacks.md
  docs/src/overview.md
  docs/src/parallelization.md
  docs/src/performance.md
Labels: documentation

#1638 add package versions to tutorials
  docs/literate/src/files/DGMulti_1.jl
  docs/literate/src/files/DGMulti_2.jl
  docs/literate/src/files/DGSEM_FluxDiff.jl
  docs/literate/src/files/adaptive_mesh_refinement.jl
  docs/literate/src/files/adding_new_parabolic_terms.jl
  docs/literate/src/files/adding_new_scalar_equations.jl
  docs/literate/src/files/adding_nonconservative_equation.jl
  docs/literate/src/files/differentiable_programming.jl
  docs/literate/src/files/hohqmesh_tutorial.jl
  docs/literate/src/files/non_periodic_boundaries.jl
  docs/literate/src/files/parabolic_terms.jl
  docs/literate/src/files/scalar_linear_advection_1d.jl
  docs/literate/src/files/shock_capturing.jl
  docs/literate/src/files/structured_mesh_mapping.jl
  docs/literate/src/files/time_stepping.jl
  docs/literate/src/files/upwind_fdsbp.jl
Labels: documentation

#1642 Increase type stab, avoid allocs
  src/solvers/dgsem_unstructured/dg_2d.jl
  test/test_threaded.jl
Labels: performance
