Repository trixi-framework/Trixi.jl, pull requests merged in 2023-07, with the labels that each got.

#1560 fix typo in docs
  docs/literate/src/files/shock_capturing.jl
Labels: documentation

#1561 Hll 2 wave improvements non breaking
  examples/dgmulti_2d/elixir_euler_bilinear.jl
  examples/dgmulti_2d/elixir_euler_curved.jl
  examples/dgmulti_2d/elixir_euler_triangulate_pkg_mesh.jl
  examples/dgmulti_2d/elixir_euler_weakform.jl
  examples/dgmulti_2d/elixir_euler_weakform_periodic.jl
  examples/dgmulti_3d/elixir_euler_curved.jl
  examples/dgmulti_3d/elixir_euler_weakform.jl
  examples/dgmulti_3d/elixir_euler_weakform_periodic.jl
  src/Trixi.jl
  src/equations/compressible_euler_1d.jl
  src/equations/compressible_euler_2d.jl
  src/equations/compressible_euler_3d.jl
  src/equations/ideal_glm_mhd_1d.jl
  src/equations/ideal_glm_mhd_2d.jl
  src/equations/ideal_glm_mhd_3d.jl
  src/equations/linearized_euler_2d.jl
  src/equations/numerical_fluxes.jl
  src/equations/shallow_water_1d.jl
  src/equations/shallow_water_2d.jl
  test/test_structured_1d.jl
  test/test_unit.jl
Labels: enhancement

#1501 Merge wet/dry capability to `main`
  NEWS.md
  examples/structured_2d_dgsem/elixir_shallowwater_conical_island.jl
  examples/structured_2d_dgsem/elixir_shallowwater_parabolic_bowl.jl
  examples/structured_2d_dgsem/elixir_shallowwater_well_balanced_wet_dry.jl
  examples/tree_1d_dgsem/elixir_shallowwater_beach.jl
  examples/tree_1d_dgsem/elixir_shallowwater_parabolic_bowl.jl
  examples/tree_1d_dgsem/elixir_shallowwater_well_balanced_wet_dry.jl
  examples/tree_2d_dgsem/elixir_shallowwater_conical_island.jl
  examples/tree_2d_dgsem/elixir_shallowwater_parabolic_bowl.jl
  examples/tree_2d_dgsem/elixir_shallowwater_well_balanced_wet_dry.jl
  examples/unstructured_2d_dgsem/elixir_shallowwater_three_mound_dam_break.jl
  src/Trixi.jl
  src/callbacks_stage/callbacks_stage.jl
  src/callbacks_stage/positivity_shallow_water.jl
  src/callbacks_stage/positivity_shallow_water_dg1d.jl
  src/callbacks_stage/positivity_shallow_water_dg2d.jl
  src/equations/numerical_fluxes.jl
  src/equations/shallow_water_1d.jl
  src/equations/shallow_water_2d.jl
  src/equations/shallow_water_two_layer_1d.jl
  src/equations/shallow_water_two_layer_2d.jl
  src/solvers/dgsem_tree/indicators.jl
  src/solvers/dgsem_tree/indicators_1d.jl
  src/solvers/dgsem_tree/indicators_2d.jl
  test/Project.toml
  test/test_structured_2d.jl
  test/test_tree_1d_shallowwater.jl
  test/test_tree_1d_shallowwater_twolayer.jl
  test/test_tree_2d_shallowwater.jl
  test/test_tree_2d_shallowwater_twolayer.jl
  test/test_unit.jl
  test/test_unstructured_2d.jl
Labels: enhancement

#1581 test threaded time integration
  examples/dgmulti_2d/elixir_euler_curved.jl
  examples/tree_2d_dgsem/elixir_advection_diffusion.jl
  examples/tree_2d_dgsem/elixir_advection_restart.jl
  test/Project.toml
  test/test_threaded.jl
Labels: testing

#1582 activate previously broken test and add allocation tests
  src/solvers/dgsem_tree/dg_1d.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_tree/dg_3d.jl
  test/test_threaded.jl
Labels: testing

#1555 Adding parabolic terms for `P4estMesh{3}`
  examples/p4est_3d_dgsem/elixir_navierstokes_convergence.jl
  examples/p4est_3d_dgsem/elixir_navierstokes_taylor_green_vortex.jl
  src/callbacks_step/analysis_dg3d.jl
  src/solvers/dgsem_p4est/dg.jl
  src/solvers/dgsem_p4est/dg_2d_parabolic.jl
  src/solvers/dgsem_p4est/dg_3d_parabolic.jl
  src/solvers/dgsem_tree/dg_3d_parabolic.jl
  test/test_parabolic_3d.jl
Labels: enhancement

#1580 Timestep stamp in mesh file
  src/callbacks_step/save_solution.jl
  test/test_mpi_tree.jl
Labels: bug

#1426 Feature: t8code as meshing backend
  .github/workflows/ci.yml
  Project.toml
  examples/t8code_2d_dgsem/elixir_advection_amr_solution_independent.jl
  examples/t8code_2d_dgsem/elixir_advection_amr_unstructured_flag.jl
  examples/t8code_2d_dgsem/elixir_advection_basic.jl
  examples/t8code_2d_dgsem/elixir_advection_nonconforming_flag.jl
  examples/t8code_2d_dgsem/elixir_advection_unstructured_flag.jl
  examples/t8code_2d_dgsem/elixir_euler_free_stream.jl
  examples/t8code_2d_dgsem/elixir_euler_sedov.jl
  examples/t8code_2d_dgsem/elixir_euler_shockcapturing_ec.jl
  examples/t8code_2d_dgsem/elixir_euler_source_terms_nonconforming_unstructured_flag.jl
  examples/t8code_2d_dgsem/elixir_eulergravity_convergence.jl
  examples/t8code_2d_dgsem/elixir_mhd_alfven_wave.jl
  examples/t8code_2d_dgsem/elixir_mhd_rotor.jl
  examples/t8code_2d_dgsem/elixir_shallowwater_source_terms.jl
  src/Trixi.jl
  src/auxiliary/t8code.jl
  src/callbacks_step/amr.jl
  src/callbacks_step/amr_dg2d.jl
  src/callbacks_step/analysis.jl
  src/callbacks_step/analysis_dg2d.jl
  src/callbacks_step/save_restart_dg.jl
  src/callbacks_step/save_solution_dg.jl
  src/callbacks_step/stepsize_dg2d.jl
  src/meshes/mesh_io.jl
  src/meshes/meshes.jl
  src/meshes/t8code_mesh.jl
  src/solvers/dg.jl
  src/solvers/dgsem_p4est/containers.jl
  src/solvers/dgsem_p4est/containers_2d.jl
  src/solvers/dgsem_p4est/dg_2d.jl
  src/solvers/dgsem_structured/dg_2d.jl
  src/solvers/dgsem_t8code/containers.jl
  src/solvers/dgsem_t8code/containers_2d.jl
  src/solvers/dgsem_t8code/dg.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_tree/indicators_2d.jl
  src/solvers/dgsem_unstructured/dg_2d.jl
  test/runtests.jl
  test/test_t8code_2d.jl
  test/test_threaded.jl
Labels: enhancement

#1593 Fix `P4estMesh` CI issues
  src/solvers/dgsem_p4est/dg_3d_parabolic.jl
Labels: bug

#1592 run only threaded tests by default
  test/runtests.jl
Labels: testing
