Repository trixi-framework/Trixi.jl, pull requests merged in 2023-01, with the labels that each got.

#1322 move GeometryBasics to Makie requires block
  Project.toml
  src/Trixi.jl
  src/visualization/recipes_makie.jl
  src/visualization/utilities.jl
Labels: visualization, latency

#1326 Fix bugs when run with MPI
  src/auxiliary/mpi.jl
  src/callbacks_step/analysis.jl
  test/test_trixi.jl
Labels: parallelization

#1338 Add documentation of distribution of cells for `P4estMesh` with MPI
  docs/src/troubleshooting.md
Labels: documentation
