Repository trixi-framework/Trixi.jl, pull requests merged in 2023-05, with the labels that each got.

#1422 fix docstring of `trixi_include`
  src/auxiliary/special_elixirs.jl
Labels: documentation

#1428 `typeof(stdout)` -> `Base.TTY` for precompile statements
  Project.toml
  src/auxiliary/precompile.jl
Labels: latency

#1432 fix definition of `init_mpi_data_structures`
  src/solvers/dgsem_p4est/dg_parallel.jl
  src/solvers/dgsem_tree/dg.jl
  src/solvers/dgsem_tree/dg_2d_parallel.jl
  src/solvers/dgsem_tree/dg_parallel.jl
Labels: bug, parallelization

#1450 restrict MPI.jl to v0.20.8
  Project.toml
Labels: bug, upstream

#1455 precompile less when running tests
  test/Project.toml
Labels: testing

#1467 change `DGMulti` `calc_surface_integral!` signature for consistency
  src/solvers/dgmulti/dg.jl
  src/solvers/dgmulti/flux_differencing.jl
  src/solvers/dgmulti/flux_differencing_gauss_sbp.jl
  src/solvers/dgmulti/sbp.jl
Labels: consistency

#1472 allow MPI.jl v0.20.*
  Project.toml
Labels: testing, upstream

#1462 Add function barrier to fix HG shock capturing on macOS ARM
  src/solvers/dgsem_tree/indicators.jl
  src/solvers/dgsem_tree/indicators_1d.jl
  src/solvers/dgsem_tree/indicators_2d.jl
  src/solvers/dgsem_tree/indicators_3d.jl
Labels: bug, parallelization

#1399 Parallel I/O
  .gitignore
  docs/src/parallelization.md
  src/Trixi.jl
  src/callbacks_step/save_restart_dg.jl
  src/callbacks_step/save_solution_dg.jl
  test/test_trixi.jl
Labels: parallelization

#1496 fix docstring of `iplot`
  src/visualization/recipes_makie.jl
Labels: documentation, visualization

#1497 move Linux MPI to separate CI job
  .github/workflows/ci.yml
  .github/workflows/ci_problematic.yml
Labels: testing

#1316 move CI to Julia 1.9
  .github/workflows/Documenter.yml
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .github/workflows/ci_problematic.yml
  README.md
  docs/src/development.md
  docs/src/index.md
  ext/TrixiMakieExt.jl
  src/Trixi.jl
  test/runtests.jl
  test/test_dgmulti_2d.jl
Labels: testing
