Repository trixi-framework/Trixi.jl, pull requests merged in 2023-12, with the labels that each got.

#1756 Use total pressure for 1D HLLC MHD
  src/equations/ideal_glm_mhd_1d.jl
  test/test_tree_1d_mhd.jl
Labels: bug

#1760 Update test vals of failing tests for upstream packages
  examples/tree_2d_dgsem/elixir_eulermulti_shock_bubble.jl
  examples/tree_2d_dgsem/elixir_eulermulti_shock_bubble_shockcapturing_subcell_minmax.jl
  examples/tree_2d_dgsem/elixir_eulermulti_shock_bubble_shockcapturing_subcell_positivity.jl
  ext/TrixiMakieExt.jl
  src/auxiliary/precompile.jl
  src/callbacks_step/averaging.jl
  src/callbacks_step/euler_acoustics_coupling.jl
  src/callbacks_step/glm_speed_dg.jl
  src/callbacks_step/save_solution.jl
  src/callbacks_step/save_solution_dg.jl
  src/equations/compressible_euler_multicomponent_1d.jl
  src/equations/compressible_euler_multicomponent_2d.jl
  src/equations/compressible_navier_stokes_1d.jl
  src/equations/compressible_navier_stokes_2d.jl
  src/equations/compressible_navier_stokes_3d.jl
  src/equations/ideal_glm_mhd_multicomponent_1d.jl
  src/equations/ideal_glm_mhd_multicomponent_2d.jl
  src/equations/numerical_fluxes.jl
  src/meshes/unstructured_mesh.jl
  src/semidiscretization/semidiscretization_coupled.jl
  src/semidiscretization/semidiscretization_hyperbolic.jl
  src/semidiscretization/semidiscretization_hyperbolic_parabolic.jl
  src/solvers/dgmulti/flux_differencing.jl
  src/solvers/dgmulti/flux_differencing_gauss_sbp.jl
  src/solvers/dgmulti/sbp.jl
  src/solvers/dgmulti/types.jl
  src/solvers/dgsem/basis_lobatto_legendre.jl
  src/solvers/dgsem_p4est/containers.jl
  src/solvers/dgsem_p4est/containers_parallel.jl
  src/solvers/dgsem_p4est/containers_parallel_2d.jl
  src/solvers/dgsem_p4est/containers_parallel_3d.jl
  src/solvers/dgsem_p4est/dg_2d_parabolic.jl
  src/solvers/dgsem_p4est/dg_parallel.jl
  src/solvers/dgsem_structured/containers.jl
  src/solvers/dgsem_tree/dg_1d_parabolic.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_tree/dg_2d_parabolic.jl
  src/solvers/dgsem_tree/dg_3d.jl
  src/solvers/dgsem_tree/dg_3d_parabolic.jl
  src/solvers/dgsem_tree/indicators_1d.jl
  src/solvers/dgsem_tree/indicators_2d.jl
  src/solvers/dgsem_tree/subcell_limiters_2d.jl
  src/visualization/recipes_plots.jl
  test/test_tree_3d_fdsbp.jl
Labels: testing, upstream

#1773 Central SBP finite difference solver for `UnstructuredMesh2D`
  examples/unstructured_2d_fdsbp/elixir_advection_basic.jl
  examples/unstructured_2d_fdsbp/elixir_euler_free_stream.jl
  examples/unstructured_2d_fdsbp/elixir_euler_source_terms.jl
  src/solvers/dg.jl
  src/solvers/dgsem_unstructured/containers_2d.jl
  src/solvers/fdsbp_tree/fdsbp_2d.jl
  src/solvers/fdsbp_unstructured/containers_2d.jl
  src/solvers/fdsbp_unstructured/fdsbp.jl
  src/solvers/fdsbp_unstructured/fdsbp_2d.jl
  test/test_unstructured_2d.jl
Labels: enhancement

#1757 Compressible Euler Quasi-1D
  examples/tree_1d_dgsem/elixir_euler_quasi_1d_discontinuous.jl
  examples/tree_1d_dgsem/elixir_euler_quasi_1d_ec.jl
  examples/tree_1d_dgsem/elixir_euler_quasi_1d_source_terms.jl
  src/Trixi.jl
  src/equations/compressible_euler_quasi_1d.jl
  src/equations/equations.jl
  test/test_tree_1d_euler.jl
  test/test_unit.jl
Labels: enhancement

#1788 hotfix: restrict DiffEqBase.jl to let CI pass
  Project.toml
Labels: testing, upstream

#1765 Parabolic Mortar for AMR `P4estMesh{3}`
  NEWS.md
  examples/p4est_3d_dgsem/elixir_navierstokes_blast_wave_amr.jl
  examples/p4est_3d_dgsem/elixir_navierstokes_taylor_green_vortex_amr.jl
  src/callbacks_step/amr_dg2d.jl
  src/equations/laplace_diffusion_3d.jl
  src/solvers/dgsem_p4est/dg_3d_parabolic.jl
  test/test_parabolic_3d.jl
Labels: enhancement

#1790 Add HLLC flux for non-cartesian meshes to CompressibleEulerEquations{2,3}D
  NEWS.md
  src/equations/compressible_euler_2d.jl
  src/equations/compressible_euler_3d.jl
  test/test_p4est_2d.jl
  test/test_p4est_3d.jl
  test/test_unit.jl
Labels: enhancement
