Repository trixi-framework/Trixi.jl, pull requests merged in 2023-04, with the labels that each got.

#1405 check for allocations from mortars
  test/test_p4est_2d.jl
  test/test_p4est_3d.jl
  test/test_tree_2d_advection.jl
  test/test_tree_3d_advection.jl
Labels: testing, upstream

#1407 fix `maxiters` detection after semicolon
  examples/p4est_2d_dgsem/elixir_euler_forward_step_amr.jl
  src/auxiliary/special_elixirs.jl
Labels: bug

#1406 Combined funding logos
  README.md
  docs/src/index.md
Labels: documentation

#1412 add SpellCheck CI
  .github/workflows/SpellCheck.yml
  .typos.toml
Labels: testing

#1357 Imex
  AUTHORS.md
  examples/tree_1d_dgsem/elixir_advection_diffusion.jl
  src/Trixi.jl
  src/auxiliary/auxiliary.jl
  src/equations/equations_parabolic.jl
  src/equations/laplace_diffusion_1d.jl
  src/semidiscretization/semidiscretization_hyperbolic_parabolic.jl
  src/solvers/dgsem_tree/dg.jl
  src/solvers/dgsem_tree/dg_1d_parabolic.jl
  test/runtests.jl
  test/test_parabolic_1d.jl
Labels: enhancement
