Repository trixi-framework/Trixi.jl, pull requests merged in 2023-11, with the labels that each got.

#1701 Migrate neural network-based indicators to new repository
  NEWS.md
  examples/tree_1d_dgsem/elixir_euler_blast_wave_neuralnetwork_perssonperaire.jl
  examples/tree_1d_dgsem/elixir_euler_blast_wave_neuralnetwork_rayhesthaven.jl
  examples/tree_2d_dgsem/elixir_euler_blast_wave_neuralnetwork_cnn.jl
  examples/tree_2d_dgsem/elixir_euler_blast_wave_neuralnetwork_perssonperaire.jl
  examples/tree_2d_dgsem/elixir_euler_blast_wave_neuralnetwork_rayhesthaven.jl
  examples/tree_2d_dgsem/elixir_euler_kelvin_helmholtz_instability_amr_neuralnetwork_perssonperaire.jl
  examples/tree_2d_dgsem/elixir_euler_sedov_blast_wave_neuralnetwork_perssonperaire.jl
  src/Trixi.jl
  src/solvers/dgsem_tree/indicators.jl
  src/solvers/dgsem_tree/indicators_1d.jl
  src/solvers/dgsem_tree/indicators_2d.jl
  test/Project.toml
  test/test_tree_1d_euler.jl
  test/test_tree_2d_euler.jl
  test/test_unit.jl
Labels: breaking

#1711 add compat bounds for stdlibs
  Project.toml
  docs/Project.toml
  test/Project.toml
Labels: upstream

#1709 Deprecate some `DGMultiMesh` constructors
  docs/literate/src/files/DGMulti_1.jl
  src/solvers/dgmulti/types.jl
Labels: breaking

#1409 add gradient variable type parameter to `AbstractEquationsParabolic`
  NEWS.md
  docs/literate/src/files/adding_new_parabolic_terms.jl
  src/Trixi.jl
  src/equations/compressible_navier_stokes_1d.jl
  src/equations/compressible_navier_stokes_2d.jl
  src/equations/compressible_navier_stokes_3d.jl
  src/equations/equations.jl
  src/equations/equations_parabolic.jl
Labels: breaking

#1719 Fix bug in 2D CEE HLLE Noncartesian flux
  src/equations/compressible_euler_2d.jl
  test/test_p4est_2d.jl
  test/test_unit.jl
Labels: bug

#1723 fix IndicatorMax with multi-threading on ARM
  src/solvers/dgsem_tree/indicators_1d.jl
  src/solvers/dgsem_tree/indicators_2d.jl
  src/solvers/dgsem_tree/indicators_3d.jl
Labels: bug

#1720 Remove AMR CB from HLLE 2D Tree test
  test/test_tree_2d_euler.jl
Labels: testing

#1508 Add new non-conservative flux for standard and two-layer shallow water equations
  examples/tree_1d_dgsem/elixir_shallowwater_twolayer_convergence.jl
  examples/tree_1d_dgsem/elixir_shallowwater_twolayer_dam_break.jl
  examples/tree_1d_dgsem/elixir_shallowwater_twolayer_well_balanced.jl
  examples/tree_2d_dgsem/elixir_shallowwater_twolayer_convergence.jl
  examples/tree_2d_dgsem/elixir_shallowwater_twolayer_well_balanced.jl
  examples/unstructured_2d_dgsem/elixir_shallowwater_twolayer_convergence.jl
  examples/unstructured_2d_dgsem/elixir_shallowwater_twolayer_dam_break.jl
  examples/unstructured_2d_dgsem/elixir_shallowwater_twolayer_well_balanced.jl
  src/Trixi.jl
  src/equations/shallow_water_1d.jl
  src/equations/shallow_water_2d.jl
  src/equations/shallow_water_two_layer_1d.jl
  src/equations/shallow_water_two_layer_2d.jl
  test/test_tree_1d_shallowwater.jl
  test/test_tree_1d_shallowwater_twolayer.jl
  test/test_tree_2d_shallowwater.jl
  test/test_tree_2d_shallowwater_twolayer.jl
  test/test_unstructured_2d.jl
Labels: breaking

#1731 Fix `flux` for quasi-1D SWE
  examples/tree_1d_dgsem/elixir_shallowwater_quasi_1d_discontinuous.jl
  src/equations/shallow_water_quasi_1d.jl
  test/test_tree_1d_shallowwater.jl
Labels: bug

#1702 HLLC Flux for Ideal MHD 1D
  src/equations/ideal_glm_mhd_1d.jl
  test/test_tree_1d_mhd.jl
  test/test_unit.jl
Labels: enhancement

#1733 HLL Davis wave speeds & Cartesian Flux Winters for polytropic Euler
  examples/tree_2d_dgsem/elixir_eulerpolytropic_convergence.jl
  src/equations/polytropic_euler_2d.jl
  test/test_structured_2d.jl
  test/test_tree_2d_eulerpolytropic.jl
  test/test_tree_2d_part2.jl
  test/test_unit.jl
Labels: enhancement, consistency

#1737 Throw error in `trixi_include` when assignment is not found
  examples/p4est_2d_dgsem/elixir_advection_restart.jl
  examples/p4est_3d_dgsem/elixir_advection_restart.jl
  examples/structured_2d_dgsem/elixir_advection_restart.jl
  examples/structured_3d_dgsem/elixir_advection_restart.jl
  examples/tree_2d_dgsem/elixir_advection_restart.jl
  examples/tree_3d_dgsem/elixir_advection_restart.jl
  examples/unstructured_2d_dgsem/elixir_euler_restart.jl
  src/auxiliary/special_elixirs.jl
  test/test_mpi_p4est_2d.jl
  test/test_mpi_p4est_3d.jl
  test/test_p4est_2d.jl
  test/test_p4est_3d.jl
  test/test_special_elixirs.jl
  test/test_structured_2d.jl
  test/test_structured_3d.jl
  test/test_threaded.jl
  test/test_tree_3d_advection.jl
  test/test_trixi.jl
  test/test_unit.jl
  test/test_unstructured_2d.jl
  test/test_visualization.jl
Labels: enhancement

#1745 Initialize p4est and t8code only if possible
  Project.toml
  src/auxiliary/p4est.jl
  src/auxiliary/t8code.jl
Labels: parallelization

#1706 Update docs on system-provided MPI including HDF5
  docs/src/parallelization.md
Labels: documentation

#1750 Fix typo and adjust some references
  docs/src/meshes/dgmulti_mesh.md
  docs/src/parallelization.md
  docs/src/performance.md
Labels: documentation

#1751 Switch (back) to Einfeldt wave-speed estimate from paper
  src/equations/ideal_glm_mhd_1d.jl
  test/test_tree_1d_mhd.jl
Labels: bug

#1748 Store capacity serial tree mesh
  src/meshes/mesh_io.jl
Labels: enhancement
