Repository trixi-framework/Trixi.jl, pull requests merged in 2023-10, with the labels that each got.

#1669 Print addition to DOF count
  src/callbacks_step/analysis.jl
  src/semidiscretization/semidiscretization_coupled.jl
  src/semidiscretization/semidiscretization_hyperbolic.jl
  src/semidiscretization/semidiscretization_hyperbolic_parabolic.jl
Labels: low-priority

#1668 fix bug in `apply_jacobian_parabolic!` for `P4estMesh`
  src/solvers/dgsem_tree/dg_2d_parabolic.jl
  src/solvers/dgsem_tree/dg_3d_parabolic.jl
  test/test_parabolic_2d.jl
Labels: bug

#1676 Add comments explaining why weak form is only for conserved terms
  src/solvers/dg.jl
  src/solvers/dgsem_structured/dg_2d.jl
  src/solvers/dgsem_structured/dg_3d.jl
  src/solvers/dgsem_tree/dg_1d.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_tree/dg_3d.jl
Labels: documentation

#1682 Passing Allocation tests
  test/test_dgmulti_1d.jl
  test/test_dgmulti_3d.jl
  test/test_p4est_3d.jl
  test/test_parabolic_1d.jl
  test/test_parabolic_2d.jl
  test/test_parabolic_3d.jl
  test/test_structured_1d.jl
  test/test_structured_3d.jl
  test/test_t8code_2d.jl
  test/test_tree_1d_advection.jl
  test/test_tree_1d_burgers.jl
  test/test_tree_1d_euler.jl
  test/test_tree_1d_eulergravity.jl
  test/test_tree_1d_eulermulti.jl
  test/test_tree_1d_fdsbp.jl
  test/test_tree_1d_mhd.jl
  test/test_tree_1d_mhdmulti.jl
  test/test_tree_1d_shallowwater.jl
  test/test_tree_1d_shallowwater_twolayer.jl
  test/test_tree_2d_acoustics.jl
  test/test_tree_2d_euler.jl
  test/test_tree_2d_euleracoustics.jl
  test/test_tree_2d_eulermulti.jl
  test/test_tree_2d_fdsbp.jl
  test/test_tree_2d_kpp.jl
  test/test_tree_2d_lbm.jl
  test/test_tree_2d_linearizedeuler.jl
  test/test_tree_2d_mhd.jl
  test/test_tree_2d_mhdmulti.jl
  test/test_tree_2d_shallowwater.jl
  test/test_tree_2d_shallowwater_twolayer.jl
  test/test_tree_3d_advection.jl
  test/test_tree_3d_euler.jl
  test/test_tree_3d_eulergravity.jl
  test/test_tree_3d_fdsbp.jl
  test/test_tree_3d_lbm.jl
  test/test_tree_3d_mhd.jl
  test/test_unstructured_2d.jl
  utils/add_alloctest.py
Labels: testing

#1660 Add example LocalPreferences.toml file to parallelization.md
  docs/src/parallelization.md
Labels: documentation

#1685 fix allocations in boundary condition of Euler double Mach elixir
  examples/p4est_2d_dgsem/elixir_euler_double_mach_amr.jl
Labels: performance

#1684 fix type instability when iterating over callbacks in simple integrators
  src/callbacks_step/save_solution.jl
  src/callbacks_step/summary.jl
  src/time_integration/methods_2N.jl
  src/time_integration/methods_3Sstar.jl
  src/time_integration/methods_SSP.jl
Labels: performance

#1686 Add timer for outer RK loop for SSPRK33
  src/time_integration/methods_SSP.jl
  test/test_tree_2d_euler.jl
  test/test_tree_2d_eulermulti.jl
Labels: consistency

#1695 Fix allocs
  src/solvers/dgmulti/dg.jl
Labels: performance
