Repository trixi-framework/Trixi.jl, pull requests merged in 2024-10, with the labels that each got.

#2037 Remove `initial_condition` from `rhs!`, `rhs_parabolic!`
  NEWS.md
  docs/literate/src/files/behind_the_scenes_simulation_setup_plots/src/rhs_structure_figure.jl
  src/semidiscretization/semidiscretization.jl
  src/semidiscretization/semidiscretization_hyperbolic.jl
  src/semidiscretization/semidiscretization_hyperbolic_parabolic.jl
  src/solvers/dgmulti/dg.jl
  src/solvers/dgmulti/dg_parabolic.jl
  src/solvers/dgmulti/flux_differencing.jl
  src/solvers/dgmulti/flux_differencing_gauss_sbp.jl
  src/solvers/dgsem_p4est/dg_2d_parabolic.jl
  src/solvers/dgsem_p4est/dg_3d_parallel.jl
  src/solvers/dgsem_structured/dg_1d.jl
  src/solvers/dgsem_structured/dg_2d.jl
  src/solvers/dgsem_structured/dg_3d.jl
  src/solvers/dgsem_tree/dg_1d.jl
  src/solvers/dgsem_tree/dg_1d_parabolic.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_tree/dg_2d_parabolic.jl
  src/solvers/dgsem_tree/dg_2d_parallel.jl
  src/solvers/dgsem_tree/dg_3d.jl
  src/solvers/dgsem_unstructured/dg_2d.jl
Labels: low-priority, breaking, consistency, refactoring

#2104 Level Info `TreeMesh` without AMR
  src/callbacks_step/analysis.jl
Labels: low-priority

#2062 Remove `normal_direction_ll` for nonconservative terms
  NEWS.md
  examples/structured_2d_dgsem/elixir_mhd_coupled.jl
  src/basic_types.jl
  src/equations/ideal_glm_mhd_2d.jl
  src/equations/ideal_glm_mhd_3d.jl
  src/equations/shallow_water_2d.jl
  src/solvers/dgmulti/dg.jl
  src/solvers/dgmulti/flux_differencing.jl
  src/solvers/dgsem_p4est/dg_2d.jl
  src/solvers/dgsem_p4est/dg_3d.jl
  src/solvers/dgsem_structured/dg_2d.jl
  src/solvers/dgsem_structured/dg_3d.jl
  src/solvers/dgsem_unstructured/dg_2d.jl
  test/test_dgmulti_2d.jl
  test/test_p4est_2d.jl
  test/test_p4est_3d.jl
  test/test_structured_2d.jl
  test/test_structured_3d.jl
  test/test_t8code_2d.jl
  test/test_threaded.jl
  test/test_type.jl
  test/test_unstructured_2d.jl
Labels: breaking

#2078 Entropy bounded limiter
  README.md
  docs/literate/src/files/shock_capturing.jl
  docs/src/index.md
  examples/p4est_3d_dgsem/elixir_mhd_amr_entropy_bounded.jl
  examples/tree_1d_dgsem/elixir_euler_blast_wave_entropy_bounded.jl
  examples/tree_2d_dgsem/elixir_euler_colliding_flow_amr_entropy_bounded.jl
  src/Trixi.jl
  src/callbacks_stage/callbacks_stage.jl
  src/callbacks_stage/entropy_bounded_limiter.jl
  src/callbacks_stage/entropy_bounded_limiter_1d.jl
  src/callbacks_stage/entropy_bounded_limiter_2d.jl
  src/callbacks_stage/entropy_bounded_limiter_3d.jl
  test/test_p4est_3d.jl
  test/test_tree_1d_euler.jl
  test/test_tree_2d_euler.jl
Labels: enhancement

#2117 Restrict `TreeMesh` to hypercube domains
  examples/tree_2d_dgsem/elixir_euler_warm_bubble.jl
  examples/tree_3d_dgsem/elixir_advection_diffusion_nonperiodic.jl
  src/meshes/tree_mesh.jl
  test/test_unit.jl
Labels: bug, breaking

#2115 Indicator `ThreeLevelCombined` unified for all `TreeMesh`es
  src/callbacks_step/amr_dg1d.jl
  src/callbacks_step/amr_dg2d.jl
Labels: enhancement, low-priority, consistency

#2136 Make `StructuredMesh` fully type-general
  src/meshes/structured_mesh.jl
Labels: consistency

#2138 Thread-Parallelize blended DG-FV
  src/solvers/dgmulti/shock_capturing.jl
  src/solvers/dgsem_tree/dg.jl
  src/solvers/dgsem_tree/dg_1d.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_tree/dg_3d.jl
Labels: performance, parallelization, refactoring
