Repository trixi-framework/Trixi.jl, pull requests merged in 2024-06, with the labels that each got.

#1909 Add numerical support of other real types (`Float32`)
  src/equations/acoustic_perturbation_2d.jl
  src/equations/compressible_euler_1d.jl
  src/equations/compressible_euler_2d.jl
  src/equations/compressible_euler_3d.jl
  test/runtests.jl
  test/test_type.jl
Labels: enhancement

#1972 fix links to JuliaCon HPC minisymposium
  README.md
Labels: documentation, upstream

#1974 Fix `entropy` for quasi-1D compressible Euler
  src/equations/compressible_euler_quasi_1d.jl
  test/test_tree_1d_euler.jl
Labels: bug

#1976 Specify version of JuliaFormatter in docs
  docs/src/styleguide.md
Labels: documentation

#1982 solve! instead of solve_steps! for PERK2
  src/time_integration/paired_explicit_runge_kutta/methods_PERK2.jl
Labels: refactoring

#1947 Add numerical support of other real types (continue)
  AUTHORS.md
  src/equations/compressible_euler_multicomponent_1d.jl
  src/equations/compressible_euler_multicomponent_2d.jl
  src/equations/compressible_euler_quasi_1d.jl
  test/test_type.jl
Labels: enhancement

#1978 Fix timings for `SemidiscretizationCoupled`
  src/semidiscretization/semidiscretization_coupled.jl
Labels: bug

#1971 Add numerical support of other real types (`linear_advection`)
  src/equations/linear_scalar_advection_1d.jl
  src/equations/linear_scalar_advection_2d.jl
  src/equations/linear_scalar_advection_3d.jl
  test/test_type.jl
Labels: enhancement

#1983 Do not set `finalstep = false` in PERK2 `step!`
  src/time_integration/paired_explicit_runge_kutta/methods_PERK2.jl
Labels: bug

#1981 Make `copy_to_coupled_boundary!` threaded
  src/semidiscretization/semidiscretization_coupled.jl
Labels: performance, parallelization

#1975 Refactor time integrator 2N and 3Star more similar to OrdinaryDiffEq.jl integrators
  AUTHORS.md
  src/time_integration/methods_2N.jl
  src/time_integration/methods_3Sstar.jl
Labels: refactoring

#1979 Avoid type instability in `SemidiscretizationCoupled`
  src/semidiscretization/semidiscretization_coupled.jl
Labels: performance

#1969 Add numerical support of other real types (`hyperbolic`)
  src/equations/hyperbolic_diffusion_1d.jl
  src/equations/hyperbolic_diffusion_2d.jl
  src/equations/hyperbolic_diffusion_3d.jl
  test/test_type.jl
Labels: enhancement

#1968 Add numerical support of other real types (`navier`)
  src/equations/compressible_navier_stokes_1d.jl
  src/equations/compressible_navier_stokes_2d.jl
  src/equations/compressible_navier_stokes_3d.jl
  test/test_type.jl
Labels: enhancement
