Repository trixi-framework/Trixi.jl, pull requests merged in 2024-11, with the labels that each got.

#2140 Use Analysis Callback `DGMulti` parabolic examples
  examples/dgmulti_2d/elixir_advection_diffusion.jl
  examples/dgmulti_2d/elixir_advection_diffusion_nonperiodic.jl
  examples/dgmulti_2d/elixir_navierstokes_convergence.jl
  examples/dgmulti_2d/elixir_navierstokes_convergence_curved.jl
  examples/dgmulti_2d/elixir_navierstokes_lid_driven_cavity.jl
  examples/dgmulti_3d/elixir_navierstokes_taylor_green_vortex.jl
  src/callbacks_step/analysis.jl
  src/callbacks_step/analysis_dgmulti.jl
Labels: bug, low-priority, consistency

#2008 New Paired Explicit Runge-Kutta Integrator: Third Order
  NEWS.md
  Project.toml
  examples/structured_1d_dgsem/elixir_burgers_perk3.jl
  examples/tree_1d_dgsem/elixir_advection_perk2.jl
  ext/TrixiNLsolveExt.jl
  src/Trixi.jl
  src/time_integration/paired_explicit_runge_kutta/methods_PERK2.jl
  src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
  src/time_integration/paired_explicit_runge_kutta/paired_explicit_runge_kutta.jl
  test/Project.toml
  test/test_structured_1d.jl
  test/test_unit.jl
Labels: enhancement, refactoring

#1939 T8codeMesh: Switching to `t8_cmesh_new_brick_{2,3}d`.
  Project.toml
  src/meshes/t8code_mesh.jl
  test/test_t8code_2d.jl
  test/test_t8code_3d.jl
Labels: refactoring

#2129 Make `TreeMesh` type general
  examples/paper_self_gravitating_gas_dynamics/elixir_eulergravity_sedov_blast_wave.jl
  examples/tree_1d_dgsem/elixir_advection_diffusion.jl
  examples/tree_2d_dgsem/elixir_mhd_ec_float32.jl
  src/auxiliary/precompile.jl
  src/meshes/abstract_tree.jl
  src/meshes/mesh_io.jl
  src/meshes/parallel_tree.jl
  src/meshes/serial_tree.jl
  src/meshes/tree_mesh.jl
  test/test_tree_2d_mhd.jl
  test/test_unit.jl
Labels: consistency

#2153 Similiarize `Structured1D` to `Tree1D`
  examples/structured_1d_dgsem/elixir_traffic_flow_lwr_greenlight.jl
  src/meshes/structured_mesh.jl
Labels: low-priority, consistency

#2154 Make T8CodeMesh fully type general
  src/meshes/t8code_mesh.jl
  src/solvers/dgsem_t8code/containers_2d.jl
  src/solvers/dgsem_t8code/containers_3d.jl
Labels: consistency

#2156 Restart `HyperbolicParabolic` with `SplitODEProblem`
  examples/tree_1d_dgsem/elixir_advection_diffusion.jl
  examples/tree_1d_dgsem/elixir_advection_diffusion_restart.jl
  src/semidiscretization/semidiscretization.jl
  src/semidiscretization/semidiscretization_hyperbolic_parabolic.jl
  test/test_parabolic_1d.jl
Labels: bug

#2144 check_periodicity_mesh_boundary_conditions with StructuredMeshView
  src/semidiscretization/semidiscretization_hyperbolic.jl
Labels: consistency

#2170 Use velocity in Navier-Stokes convergence tests
  examples/dgmulti_2d/elixir_advection_diffusion.jl
  examples/dgmulti_2d/elixir_navierstokes_convergence.jl
  examples/dgmulti_2d/elixir_navierstokes_convergence_curved.jl
  examples/dgmulti_2d/elixir_navierstokes_lid_driven_cavity.jl
  examples/dgmulti_3d/elixir_navierstokes_convergence.jl
  examples/dgmulti_3d/elixir_navierstokes_convergence_curved.jl
  examples/p4est_2d_dgsem/elixir_navierstokes_NACA0012airfoil_mach08.jl
  examples/p4est_2d_dgsem/elixir_navierstokes_convergence.jl
  examples/p4est_2d_dgsem/elixir_navierstokes_convergence_nonperiodic.jl
  examples/p4est_2d_dgsem/elixir_navierstokes_lid_driven_cavity.jl
  examples/p4est_2d_dgsem/elixir_navierstokes_lid_driven_cavity_amr.jl
  examples/p4est_3d_dgsem/elixir_navierstokes_convergence.jl
  examples/tree_1d_dgsem/elixir_navierstokes_convergence_walls.jl
  examples/tree_1d_dgsem/elixir_navierstokes_convergence_walls_amr.jl
  examples/tree_2d_dgsem/elixir_navierstokes_convergence.jl
  examples/tree_2d_dgsem/elixir_navierstokes_lid_driven_cavity.jl
  examples/tree_3d_dgsem/elixir_navierstokes_convergence.jl
  test/test_parabolic_1d.jl
  test/test_parabolic_2d.jl
  test/test_parabolic_3d.jl
Labels: bug, consistency, refactoring

#2101 Denote pseudo time for Euler-Gravity
  src/semidiscretization/semidiscretization_euler_gravity.jl
Labels: low-priority, refactoring

#2179 Correct name for LBM book author: Timm Krüger
  src/equations/lattice_boltzmann_2d.jl
  src/equations/lattice_boltzmann_3d.jl
Labels: low-priority, refactoring

#2173 Navier-Stokes Test Case: Viscous Shock propagation
  examples/p4est_2d_dgsem/elixir_navierstokes_viscous_shock.jl
  examples/p4est_3d_dgsem/elixir_navierstokes_viscous_shock.jl
  examples/structured_1d_dgsem/elixir_traffic_flow_lwr_greenlight.jl
  examples/tree_1d_dgsem/elixir_navierstokes_viscous_shock.jl
  src/equations/compressible_navier_stokes_1d.jl
  src/equations/compressible_navier_stokes_2d.jl
  src/equations/compressible_navier_stokes_3d.jl
  test/test_parabolic_1d.jl
  test/test_parabolic_2d.jl
  test/test_parabolic_3d.jl
Labels: enhancement, testing

#2182 Time StepCallbacks for custom integrators
  src/time_integration/methods_2N.jl
  src/time_integration/methods_3Sstar.jl
  src/time_integration/methods_SSP.jl
Labels: low-priority, consistency
