Repository trixi-framework/Trixi.jl, pull requests merged in 2024-03, with the labels that each got.

#1858 force new FFMPEG.jl version for tests
  test/Project.toml
Labels: testing, upstream

#1860 Check BCs for periodicity for periodic Tree & Structured meshes
  examples/structured_2d_dgsem/elixir_advection_coupled.jl
  examples/structured_2d_dgsem/elixir_euler_rayleigh_taylor_instability.jl
  examples/structured_2d_dgsem/elixir_euler_warm_bubble.jl
  src/meshes/tree_mesh.jl
  src/semidiscretization/semidiscretization_hyperbolic.jl
  src/semidiscretization/semidiscretization_hyperbolic_parabolic.jl
Labels: bug, enhancement, low-priority, refactoring

#1863 Add warning about polynomial degree 0
  src/solvers/dgsem/basis_lobatto_legendre.jl
Labels: documentation

#1864 Update parallelization.md
  docs/src/parallelization.md
Labels: documentation

#1866 Mention hyphen/dash caveat for boundary symbols
  docs/src/meshes/p4est_mesh.md
Labels: documentation

#1870 TreeMesh 2D simulation with MPI crashes when a rank has no boundaries
  src/solvers/dgsem_tree/containers_2d.jl
Labels: bug, parallelization

#1868 remove some minor allocations for threaded FDSBP
  src/solvers/dgsem_unstructured/dg_2d.jl
  src/solvers/fdsbp_unstructured/fdsbp_2d.jl
Labels: performance

#1874 Docstrings for some methods in basis Lobatto-Legendre
  docs/literate/src/files/scalar_linear_advection_1d.jl
  src/solvers/dgsem/basis_lobatto_legendre.jl
Labels: documentation

#1873 Extend TimeSeriesCallback for TreeMesh1D/3D
  NEWS.md
  examples/tree_1d_dgsem/elixir_euler_source_terms.jl
  examples/tree_3d_dgsem/elixir_euler_source_terms.jl
  src/callbacks_step/time_series.jl
  src/callbacks_step/time_series_dg.jl
  src/callbacks_step/time_series_dg_tree.jl
  src/callbacks_step/time_series_dg_unstructured.jl
  test/test_tree_1d_euler.jl
  test/test_tree_3d_euler.jl
Labels: enhancement

#1875 Add ExplicitImports.jl test
  Project.toml
  src/Trixi.jl
  src/auxiliary/auxiliary.jl
  test/Project.toml
  test/test_aqua.jl
Labels: testing

#1812 Add AnalysisSurfaceIntegral
  NEWS.md
  examples/p4est_2d_dgsem/elixir_euler_NACA0012airfoil_mach085.jl
  examples/p4est_2d_dgsem/elixir_euler_subsonic_cylinder.jl
  examples/p4est_2d_dgsem/elixir_navierstokes_NACA0012airfoil_mach08.jl
  src/Trixi.jl
  src/callbacks_step/analysis.jl
  src/callbacks_step/analysis_surface_integral_2d.jl
  src/solvers/dgsem_p4est/dg.jl
  src/solvers/dgsem_unstructured/sort_boundary_conditions.jl
  test/test_p4est_2d.jl
  test/test_parabolic_2d.jl
Labels: enhancement
