Repository trixi-framework/Trixi.jl, pull requests merged in 2024-09, with the labels that each got.

#2057 Fix typo comment `parallel_tree.jl`
  src/meshes/parallel_tree.jl
Labels: low-priority, refactoring

#2060 Show for Indicator Vortex
  examples/tree_2d_dgsem/elixir_euler_vortex_amr.jl
Labels: low-priority

#2059 MPI: Comments & Renamings
  src/callbacks_step/amr.jl
  src/meshes/parallel_tree_mesh.jl
  src/solvers/dgsem_p4est/dg_parallel.jl
  src/solvers/dgsem_t8code/dg_parallel.jl
  src/solvers/dgsem_tree/containers_2d.jl
  src/solvers/dgsem_tree/dg_2d_parallel.jl
Labels: parallelization, low-priority, refactoring

#2052 Replace mutable structs using `Accessors`
  Project.toml
  src/Trixi.jl
  src/callbacks_step/glm_speed.jl
  src/equations/ideal_glm_mhd_2d.jl
  src/equations/ideal_glm_mhd_3d.jl
  src/equations/ideal_glm_mhd_multicomponent_1d.jl
  src/equations/ideal_glm_mhd_multicomponent_2d.jl
  src/semidiscretization/semidiscretization_coupled.jl
  src/semidiscretization/semidiscretization_hyperbolic.jl
Labels: refactoring

#2068 Add type parameter `NDIMS_AMBIENT` to `P4estMesh` for dimension of ambient space
  src/callbacks_step/analysis_dg2d.jl
  src/callbacks_step/analysis_dg3d.jl
  src/meshes/p4est_mesh.jl
  src/solvers/dgsem_p4est/containers.jl
  src/solvers/dgsem_p4est/containers_2d.jl
Labels: breaking

#2054 Use Base.min / Base.max in MPI reductions
  src/auxiliary/math.jl
  src/callbacks_step/analysis.jl
  src/callbacks_step/analysis_dg2d_parallel.jl
  src/callbacks_step/analysis_dg3d_parallel.jl
  src/callbacks_step/stepsize_dg2d.jl
  src/callbacks_step/stepsize_dg3d.jl
Labels: parallelization

#2079 Comments for more allocs for custom ODE solvers
  test/test_p4est_2d.jl
  test/test_structured_2d.jl
  test/test_tree_1d_advection.jl
  test/test_tree_1d_hypdiff.jl
  test/test_tree_2d_advection.jl
  test/test_tree_2d_euler.jl
  test/test_tree_2d_eulermulti.jl
  test/test_tree_2d_hypdiff.jl
  test/test_tree_2d_mhd.jl
  test/test_tree_3d_hypdiff.jl
Labels: low-priority, refactoring

#2077 Add function to calculate optimal CFL number for PERK2 integrator and related updates
  examples/tree_1d_dgsem/elixir_advection_perk2_optimal_cfl.jl
  src/time_integration/paired_explicit_runge_kutta/methods_PERK2.jl
  test/test_tree_1d_advection.jl
  test/test_unit.jl
Labels: enhancement, breaking

#2087 `remake` for `SemidiscretizationEulerGravity`
  src/semidiscretization/semidiscretization_euler_gravity.jl
  test/test_special_elixirs.jl
Labels: enhancement

#2089 Stable CFL EG Jeans
  examples/paper_self_gravitating_gas_dynamics/elixir_eulergravity_jeans_instability.jl
  test/test_paper_self_gravitating_gas_dynamics.jl
Labels: bug

#2083 Implement a function to calculate the optimal CFL number for the PERK2 integrator and apply the necessary related updates
  examples/tree_1d_dgsem/elixir_advection_perk2_optimal_cfl.jl
  src/time_integration/paired_explicit_runge_kutta/methods_PERK2.jl
  test/test_tree_1d_advection.jl
  test/test_unit.jl
Labels: enhancement, breaking
