Repository trixi-framework/Trixi.jl, pull requests merged in 2024-08, with the labels that each got.

#2021 Add numerical support for other real types (`fluxes`)
  src/equations/numerical_fluxes.jl
  test/test_type.jl
Labels: enhancement

#2002 Add numerical support of other real types (`linearized_euler`)
  src/equations/linearized_euler_2d.jl
  test/test_type.jl
Labels: enhancement

#2041 More accurate comments MPI Mortar Containers
  src/solvers/dgsem_p4est/containers_parallel.jl
  src/solvers/dgsem_tree/containers_2d.jl
Labels: low-priority

#2030 Note new file name in benchmark docs
  docs/src/performance.md
Labels: documentation

#2015 Add numerical support of other real types (`polytropic_euler`)
  src/equations/polytropic_euler_2d.jl
  test/test_type.jl
Labels: enhancement

#2025 Add numerical support of other real types (`laplace`)
  test/test_type.jl
Labels: enhancement

#1954 Add subcell limiting support for P4estMesh
  examples/p4est_2d_dgsem/elixir_euler_sedov_blast_wave_sc_subcell.jl
  examples/p4est_2d_dgsem/elixir_euler_supersonic_cylinder_sc_subcell.jl
  src/callbacks_stage/subcell_bounds_check.jl
  src/callbacks_stage/subcell_bounds_check_2d.jl
  src/callbacks_stage/subcell_limiter_idp_correction_2d.jl
  src/solvers/dgsem_p4est/dg.jl
  src/solvers/dgsem_p4est/subcell_limiters_2d.jl
  src/solvers/dgsem_structured/dg_2d_subcell_limiters.jl
  src/solvers/dgsem_structured/subcell_limiters_2d.jl
  src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
  src/solvers/dgsem_tree/subcell_limiters.jl
  src/solvers/dgsem_tree/subcell_limiters_2d.jl
  test/test_p4est_2d.jl
Labels: enhancement
