Repository trixi-framework/Trixi.jl, pull requests merged in 2024-07, with the labels that each got.

#1959 AMR-Compat SurfaceIntegrals
  NEWS.md
  examples/p4est_2d_dgsem/elixir_euler_NACA0012airfoil_mach085.jl
  examples/p4est_2d_dgsem/elixir_euler_subsonic_cylinder.jl
  examples/p4est_2d_dgsem/elixir_navierstokes_NACA0012airfoil_mach08.jl
  src/callbacks_step/analysis.jl
  src/callbacks_step/analysis_surface_integral_2d.jl
  test/test_p4est_2d.jl
  test/test_parabolic_2d.jl
Labels: bug, enhancement, breaking, refactoring

#1996 Add more zeros to solution file name
  NEWS.md
  docs/Project.toml
  docs/literate/src/files/first_steps/create_first_setup.jl
  docs/literate/src/files/hohqmesh_tutorial.jl
  docs/src/restart.md
  docs/src/visualization.md
  examples/p4est_2d_dgsem/elixir_advection_restart.jl
  examples/p4est_2d_dgsem/elixir_advection_restart_amr.jl
  examples/p4est_3d_dgsem/elixir_advection_restart.jl
  examples/structured_2d_dgsem/elixir_advection_restart.jl
  examples/structured_3d_dgsem/elixir_advection_restart.jl
  examples/tree_2d_dgsem/elixir_advection_restart.jl
  examples/tree_2d_dgsem/elixir_advection_restart_amr.jl
  examples/tree_3d_dgsem/elixir_advection_restart.jl
  examples/unstructured_2d_dgsem/elixir_euler_restart.jl
  src/callbacks_step/save_restart_dg.jl
  src/callbacks_step/save_solution_dg.jl
  src/callbacks_step/visualization.jl
  src/meshes/mesh_io.jl
  src/meshes/structured_mesh_view.jl
  test/test_structured_2d.jl
  test/test_threaded.jl
  test/test_visualization.jl
  utils/plot.gp
Labels: breaking

#1984 Add numerical support of other real types (`ideal`)
  src/equations/ideal_glm_mhd_1d.jl
  src/equations/ideal_glm_mhd_2d.jl
  src/equations/ideal_glm_mhd_3d.jl
  test/test_type.jl
Labels: enhancement, testing

#1999 fix changelog in docs
  NEWS.md
  docs/make.jl
Labels: bug, documentation

#1986 Add StructuredMeshView to fluxes.
  src/solvers/dgsem_structured/dg_2d.jl
  src/solvers/dgsem_tree/dg_2d.jl
Labels: enhancement

#2003 Update docstring `AnalysisSurfaceIntegral`
  src/callbacks_step/analysis_surface_integral_2d.jl
Labels: documentation

#1949 Maxwell 1D (Wave Equation)
  examples/tree_1d_dgsem/elixir_maxwell_E_excitation.jl
  examples/tree_1d_dgsem/elixir_maxwell_convergence.jl
  src/Trixi.jl
  src/equations/equations.jl
  src/equations/maxwell_1d.jl
  test/test_tree_1d.jl
  test/test_tree_1d_maxwell.jl
  test/test_unit.jl
Labels: enhancement

#1988 Add numerical support of other real types (`multi`)
  src/equations/compressible_euler_multicomponent_1d.jl
  src/equations/compressible_euler_multicomponent_2d.jl
  src/equations/ideal_glm_mhd_multicomponent_1d.jl
  src/equations/ideal_glm_mhd_multicomponent_2d.jl
  src/equations/inviscid_burgers_1d.jl
  test/test_type.jl
Labels: enhancement, testing

#2004 Bug fix for polynomial optimization for PERK integrator
  ext/TrixiConvexECOSExt.jl
Labels: bug

#2006 Canonical use of `initial_condition`
  examples/tree_1d_dgsem/elixir_advection_diffusion.jl
Labels: consistency, refactoring

#2009 Update benchmarks.jl: 1D
  benchmark/benchmarks.jl
Labels: testing

#1991 Add numerical support of other real types (`lattice`)
  src/equations/lattice_boltzmann_2d.jl
  src/equations/lattice_boltzmann_3d.jl
  test/test_type.jl
  test/test_unit.jl
Labels: enhancement, testing

#1995 Add numerical support of other real types (`water`)
  src/equations/shallow_water_1d.jl
  src/equations/shallow_water_2d.jl
  src/equations/shallow_water_quasi_1d.jl
  test/test_type.jl
Labels: enhancement

#2018 Update feature table: parabolic terms not supported for `StructuredMesh`
  docs/src/overview.md
Labels: documentation

#2014 `calc_volume_integral!` for all meshes supported by `fv_kernel!`
  src/solvers/dgsem_tree/dg_1d.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_tree/dg_3d.jl
  test/test_p4est_2d.jl
  test/test_structured_1d.jl
  test/test_t8code_3d.jl
Labels: consistency

#2011 Add numerical support of other real types (`maxwell`)
  src/equations/maxwell_1d.jl
  test/test_type.jl
Labels: enhancement
