Repository trixi-framework/Trixi.jl, pull requests merged in 2024-12, with the labels that each got.

#2180 More efficient PERK implementation
  examples/structured_1d_dgsem/elixir_burgers_perk3.jl
  examples/tree_1d_dgsem/elixir_advection_perk2.jl
  ext/TrixiConvexECOSExt.jl
  ext/TrixiNLsolveExt.jl
  src/time_integration/paired_explicit_runge_kutta/methods_PERK2.jl
  src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
  src/time_integration/paired_explicit_runge_kutta/paired_explicit_runge_kutta.jl
  test/test_structured_1d.jl
  test/test_unit.jl
Labels: performance, refactoring

#2128 Arbitrary Precision LGL Basis
  NEWS.md
  README.md
  docs/src/index.md
  examples/structured_1d_dgsem/elixir_advection_float128.jl
  examples/tree_1d_dgsem/elixir_advection_doublefloat.jl
  src/auxiliary/precompile.jl
  src/auxiliary/special_elixirs.jl
  src/callbacks_step/analysis_dg1d.jl
  src/callbacks_step/analysis_dg2d.jl
  src/callbacks_step/analysis_dg2d_parallel.jl
  src/callbacks_step/analysis_dg3d.jl
  src/callbacks_step/analysis_dg3d_parallel.jl
  src/solvers/dgsem/basis_lobatto_legendre.jl
  src/solvers/dgsem/l2projection.jl
  test/Project.toml
  test/test_p4est_2d.jl
  test/test_structured_1d.jl
  test/test_tree_1d_advection.jl
  test/test_tree_2d_mhd.jl
  test/test_trixi.jl
  test/test_unit.jl
  test/test_unstructured_2d.jl
Labels: enhancement

#2168 Enable GPU compatibility check in CI
  .github/workflows/GPUCompat.yml
Labels: testing, gpu

#2172 Fix: Automatically finalize t8code objects when Trixi.jl shuts down
  Project.toml
  examples/t8code_2d_dgsem/elixir_advection_amr_solution_independent.jl
  examples/t8code_2d_dgsem/elixir_advection_amr_unstructured_flag.jl
  examples/t8code_2d_dgsem/elixir_advection_basic.jl
  examples/t8code_2d_dgsem/elixir_advection_extended.jl
  examples/t8code_2d_dgsem/elixir_advection_nonconforming_flag.jl
  examples/t8code_2d_dgsem/elixir_advection_restart.jl
  examples/t8code_2d_dgsem/elixir_advection_restart_amr.jl
  examples/t8code_2d_dgsem/elixir_advection_unstructured_flag.jl
  examples/t8code_2d_dgsem/elixir_euler_free_stream.jl
  examples/t8code_2d_dgsem/elixir_euler_sedov.jl
  examples/t8code_2d_dgsem/elixir_euler_shockcapturing_ec.jl
  examples/t8code_2d_dgsem/elixir_euler_source_terms_nonconforming_unstructured_flag.jl
  examples/t8code_2d_dgsem/elixir_euler_weak_blast_wave_amr.jl
  examples/t8code_2d_dgsem/elixir_eulergravity_convergence.jl
  examples/t8code_2d_dgsem/elixir_mhd_alfven_wave.jl
  examples/t8code_2d_dgsem/elixir_mhd_rotor.jl
  examples/t8code_2d_dgsem/elixir_shallowwater_source_terms.jl
  examples/t8code_3d_dgsem/elixir_advection_amr.jl
  examples/t8code_3d_dgsem/elixir_advection_amr_unstructured_curved.jl
  examples/t8code_3d_dgsem/elixir_advection_basic.jl
  examples/t8code_3d_dgsem/elixir_advection_nonconforming.jl
  examples/t8code_3d_dgsem/elixir_advection_restart.jl
  examples/t8code_3d_dgsem/elixir_advection_unstructured_curved.jl
  examples/t8code_3d_dgsem/elixir_euler_ec.jl
  examples/t8code_3d_dgsem/elixir_euler_free_stream.jl
  examples/t8code_3d_dgsem/elixir_euler_free_stream_extruded.jl
  examples/t8code_3d_dgsem/elixir_euler_sedov.jl
  examples/t8code_3d_dgsem/elixir_euler_source_terms_nonconforming_unstructured_curved.jl
  examples/t8code_3d_dgsem/elixir_euler_source_terms_nonperiodic.jl
  examples/t8code_3d_dgsem/elixir_euler_weak_blast_wave_amr.jl
  examples/tree_3d_dgsem/elixir_euler_convergence_pure_fv.jl
  src/auxiliary/t8code.jl
  src/meshes/t8code_mesh.jl
Labels: enhancement, refactoring

#2146 Update Documentation: Optimized Schemes, PERK Section, and PairedExplicitRK2 Tutorial
  docs/Project.toml
  docs/src/time_integration.md
Labels: documentation

#2188 Remove unused `surface_integral` for `prolong2mortar` functions
  src/solvers/dgsem_p4est/dg_2d.jl
  src/solvers/dgsem_p4est/dg_2d_parabolic.jl
  src/solvers/dgsem_p4est/dg_2d_parallel.jl
  src/solvers/dgsem_p4est/dg_3d.jl
  src/solvers/dgsem_p4est/dg_3d_parabolic.jl
  src/solvers/dgsem_p4est/dg_3d_parallel.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_tree/dg_2d_parabolic.jl
  src/solvers/dgsem_tree/dg_2d_parallel.jl
  src/solvers/dgsem_tree/dg_3d.jl
  src/solvers/dgsem_tree/dg_3d_parabolic.jl
  src/solvers/fdsbp_tree/fdsbp.jl
Labels: low-priority, consistency, refactoring

#2192 Remove unused variables in elixir_advection_diffusion_nonperiodic_curved.jl
  examples/p4est_2d_dgsem/elixir_advection_diffusion_nonperiodic_curved.jl
Labels: low-priority

#2191 Pass on `RealT` in `TreeMesh` construction
  src/meshes/parallel_tree.jl
  src/meshes/serial_tree.jl
  src/meshes/tree_mesh.jl
  test/test_type.jl
Labels: bug, performance

#2202 Semantic code order for Multi Equations Constructors
  src/equations/compressible_euler_multicomponent_1d.jl
  src/equations/compressible_euler_multicomponent_2d.jl
  src/equations/ideal_glm_mhd_multicomponent_1d.jl
  src/equations/ideal_glm_mhd_multicomponent_2d.jl
Labels: low-priority, refactoring

#2206 Reduction for `linf_divb` analysis
  src/callbacks_step/analysis_dg1d.jl
  src/callbacks_step/analysis_dg2d.jl
  src/callbacks_step/analysis_dg3d.jl
  src/callbacks_step/analysis_dgmulti.jl
Labels: performance, parallelization, low-priority

#2207 Use reduction for max wave speed computation in `max_dt`
  src/callbacks_step/stepsize_dg1d.jl
  src/callbacks_step/stepsize_dg2d.jl
  src/callbacks_step/stepsize_dg3d.jl
Labels: performance, parallelization

#2208 fix StructuredMesh docstrings
  src/meshes/structured_mesh.jl
Labels: documentation

#2209 fix docstrings of shallow water equations
  src/equations/shallow_water_1d.jl
  src/equations/shallow_water_2d.jl
  src/equations/shallow_water_quasi_1d.jl
Labels: documentation
