Repository trixi-framework/Trixi.jl, pull requests merged in 2024-02, with the labels that each got.

#1807 Move Jacobian for para P4est to respective files, add muladd
  src/solvers/dgsem_p4est/dg_2d_parabolic.jl
  src/solvers/dgsem_p4est/dg_3d_parabolic.jl
  src/solvers/dgsem_tree/dg_2d_parabolic.jl
  src/solvers/dgsem_tree/dg_3d_parabolic.jl
  test/test_parabolic_2d.jl
Labels: consistency

#1819 Add section about false sharing problems to documentation
  docs/src/performance.md
Labels: documentation

#1829 Add entry for gmsh tutorial in introduction
  docs/literate/src/files/index.jl
Labels: documentation

#1834 Make CI fail if Codecov fails
  .github/workflows/ci.yml
Labels: testing

#1777 coverallsapp at v2
  .github/workflows/ci.yml
Labels: testing

#1840 Classic LWR traffic flow
  NEWS.md
  README.md
  examples/structured_1d_dgsem/elixir_traffic_flow_lwr_greenlight.jl
  examples/tree_1d_dgsem/elixir_traffic_flow_lwr_convergence.jl
  examples/tree_1d_dgsem/elixir_traffic_flow_lwr_trafficjam.jl
  src/Trixi.jl
  src/equations/equations.jl
  src/equations/traffic_flow_lwr_1d.jl
  test/test_structured_1d.jl
  test/test_tree_1d.jl
  test/test_tree_1d_traffic_flow_lwr.jl
Labels: enhancement

#1699 Doc: Core aspects of the basic setup
  docs/literate/src/files/behind_the_scenes_simulation_setup.jl
  docs/literate/src/files/behind_the_scenes_simulation_setup_plots/Project.toml
  docs/literate/src/files/behind_the_scenes_simulation_setup_plots/README.md
  docs/literate/src/files/behind_the_scenes_simulation_setup_plots/src/SemidiscretizationHyperbolic_structure_figure.jl
  docs/literate/src/files/behind_the_scenes_simulation_setup_plots/src/generate_boundary_figure.jl
  docs/literate/src/files/behind_the_scenes_simulation_setup_plots/src/generate_elements_figure.jl
  docs/literate/src/files/behind_the_scenes_simulation_setup_plots/src/generate_interfaces_figure.jl
  docs/literate/src/files/behind_the_scenes_simulation_setup_plots/src/generate_mortars_figure.jl
  docs/literate/src/files/behind_the_scenes_simulation_setup_plots/src/generate_nodes_figure.jl
  docs/literate/src/files/behind_the_scenes_simulation_setup_plots/src/generate_treemesh_figure.jl
  docs/literate/src/files/behind_the_scenes_simulation_setup_plots/src/rhs_structure_figure.jl
  docs/literate/src/files/behind_the_scenes_simulation_setup_plots/src/semidiscretize_structure_figure.jl
  docs/literate/src/files/index.jl
  docs/make.jl
Labels: documentation

#1849 Update benchmarking docs
  docs/src/performance.md
Labels: documentation

#1781 Own `sqrt` and `log` returning `NaN` for "correct" multi-thread behaviour
  .github/workflows/Downgrade.yml
  Project.toml
  src/Trixi.jl
  src/auxiliary/math.jl
  test/test_parabolic_1d.jl
  test/test_unstructured_2d.jl
Labels: performance, breaking

#1809 Separation of TrixiShallowWater.jl
  NEWS.md
  examples/structured_2d_dgsem/elixir_shallowwater_conical_island.jl
  examples/structured_2d_dgsem/elixir_shallowwater_parabolic_bowl.jl
  examples/structured_2d_dgsem/elixir_shallowwater_well_balanced_wet_dry.jl
  examples/tree_1d_dgsem/elixir_shallowwater_beach.jl
  examples/tree_1d_dgsem/elixir_shallowwater_parabolic_bowl.jl
  examples/tree_1d_dgsem/elixir_shallowwater_twolayer_convergence.jl
  examples/tree_1d_dgsem/elixir_shallowwater_twolayer_dam_break.jl
  examples/tree_1d_dgsem/elixir_shallowwater_twolayer_well_balanced.jl
  examples/tree_1d_dgsem/elixir_shallowwater_well_balanced_wet_dry.jl
  examples/tree_2d_dgsem/elixir_shallowwater_conical_island.jl
  examples/tree_2d_dgsem/elixir_shallowwater_parabolic_bowl.jl
  examples/tree_2d_dgsem/elixir_shallowwater_twolayer_convergence.jl
  examples/tree_2d_dgsem/elixir_shallowwater_twolayer_well_balanced.jl
  examples/tree_2d_dgsem/elixir_shallowwater_well_balanced_wet_dry.jl
  examples/unstructured_2d_dgsem/elixir_shallowwater_three_mound_dam_break.jl
  examples/unstructured_2d_dgsem/elixir_shallowwater_twolayer_convergence.jl
  examples/unstructured_2d_dgsem/elixir_shallowwater_twolayer_dam_break.jl
  examples/unstructured_2d_dgsem/elixir_shallowwater_twolayer_well_balanced.jl
  src/Trixi.jl
  src/callbacks_stage/callbacks_stage.jl
  src/callbacks_stage/positivity_shallow_water.jl
  src/callbacks_stage/positivity_shallow_water_dg1d.jl
  src/callbacks_stage/positivity_shallow_water_dg2d.jl
  src/equations/equations.jl
  src/equations/numerical_fluxes.jl
  src/equations/shallow_water_1d.jl
  src/equations/shallow_water_2d.jl
  src/equations/shallow_water_quasi_1d.jl
  src/equations/shallow_water_two_layer_1d.jl
  src/equations/shallow_water_two_layer_2d.jl
  src/solvers/dgsem_tree/indicators.jl
  src/solvers/dgsem_tree/indicators_1d.jl
  src/solvers/dgsem_tree/indicators_2d.jl
  test/test_structured_2d.jl
  test/test_tree_1d.jl
  test/test_tree_1d_shallowwater.jl
  test/test_tree_1d_shallowwater_twolayer.jl
  test/test_tree_2d_part3.jl
  test/test_tree_2d_shallowwater.jl
  test/test_tree_2d_shallowwater_twolayer.jl
  test/test_unit.jl
  test/test_unstructured_2d.jl
Labels: breaking

#1743 Make `min_max_speed_davis` default wave speed estimate for `FluxHLL()`
  NEWS.md
  examples/p4est_2d_dgsem/elixir_eulergravity_convergence.jl
  examples/p4est_3d_dgsem/elixir_euler_source_terms_nonconforming_earth.jl
  examples/paper_self_gravitating_gas_dynamics/elixir_euler_convergence.jl
  examples/paper_self_gravitating_gas_dynamics/elixir_eulergravity_convergence.jl
  examples/paper_self_gravitating_gas_dynamics/elixir_eulergravity_jeans_instability.jl
  examples/paper_self_gravitating_gas_dynamics/elixir_eulergravity_sedov_blast_wave.jl
  examples/t8code_2d_dgsem/elixir_eulergravity_convergence.jl
  examples/tree_1d_dgsem/elixir_shallowwater_well_balanced_nonperiodic.jl
  examples/tree_3d_dgsem/elixir_eulergravity_convergence.jl
  examples/unstructured_2d_dgsem/elixir_shallowwater_dirichlet.jl
  src/equations/numerical_fluxes.jl
  test/test_dgmulti_1d.jl
  test/test_dgmulti_2d.jl
  test/test_dgmulti_3d.jl
  test/test_parabolic_3d.jl
  test/test_special_elixirs.jl
  test/test_structured_2d.jl
  test/test_threaded.jl
  test/test_tree_1d_euler.jl
  test/test_tree_1d_eulergravity.jl
  test/test_tree_1d_shallowwater.jl
  test/test_tree_2d_mhd.jl
  test/test_tree_2d_shallowwater.jl
  test/test_tree_3d_euler.jl
  test/test_tree_3d_mhd.jl
  test/test_unstructured_2d.jl
Labels: breaking
