Repository trixi-framework/Trixi.jl, pull requests merged in 2024-04, with the labels that each got.

#1867 1D Linearized Euler
  NEWS.md
  examples/structured_1d_dgsem/elixir_linearizedeuler_characteristic_system.jl
  examples/tree_1d_dgsem/elixir_linearizedeuler_convergence.jl
  examples/tree_1d_dgsem/elixir_linearizedeuler_gauss_wall.jl
  src/Trixi.jl
  src/equations/equations.jl
  src/equations/linearized_euler_1d.jl
  test/test_structured_1d.jl
  test/test_tree_1d.jl
  test/test_tree_1d_linearizedeuler.jl
Labels: enhancement

#1897 Math rendering speed of sound docstring linearized Euler Eqs
  src/equations/linearized_euler_1d.jl
  src/equations/linearized_euler_2d.jl
Labels: documentation

#1898 Fix computation of `max_abs_speeds` for the SWE
  examples/structured_2d_dgsem/elixir_shallowwater_source_terms.jl
  examples/structured_2d_dgsem/elixir_shallowwater_well_balanced.jl
  examples/tree_1d_dgsem/elixir_shallowwater_ec.jl
  examples/tree_1d_dgsem/elixir_shallowwater_quasi_1d_well_balanced.jl
  examples/tree_1d_dgsem/elixir_shallowwater_well_balanced.jl
  examples/tree_2d_dgsem/elixir_shallowwater_ec.jl
  examples/tree_2d_dgsem/elixir_shallowwater_well_balanced.jl
  examples/tree_2d_dgsem/elixir_shallowwater_well_balanced_wall.jl
  examples/unstructured_2d_dgsem/elixir_shallowwater_ec.jl
  examples/unstructured_2d_dgsem/elixir_shallowwater_ec_shockcapturing.jl
  examples/unstructured_2d_dgsem/elixir_shallowwater_well_balanced.jl
  src/equations/shallow_water_1d.jl
  src/equations/shallow_water_2d.jl
  src/equations/shallow_water_quasi_1d.jl
  test/test_structured_2d.jl
  test/test_tree_1d_shallowwater.jl
  test/test_tree_2d_shallowwater.jl
  test/test_unstructured_2d.jl
Labels: bug

#1893 Boundary integration of viscous forces
  examples/p4est_2d_dgsem/elixir_navierstokes_NACA0012airfoil_mach08.jl
  src/Trixi.jl
  src/callbacks_step/analysis.jl
  src/callbacks_step/analysis_surface_integral_2d.jl
  test/test_parabolic_2d.jl
Labels: enhancement

#1899 Use `eachindex` instead of `1:length`, compare against `nothing` with `===`
  docs/literate/src/files/non_periodic_boundaries.jl
  docs/literate/src/files/scalar_linear_advection_1d.jl
  examples/p4est_2d_dgsem/elixir_advection_amr_solution_independent.jl
  examples/t8code_2d_dgsem/elixir_advection_amr_solution_independent.jl
  examples/tree_2d_dgsem/elixir_advection_amr_solution_independent.jl
  src/callbacks_step/amr.jl
  src/callbacks_step/euler_acoustics_coupling_dg2d.jl
  src/callbacks_step/time_series_dg_tree.jl
  src/callbacks_step/time_series_dg_unstructured.jl
  src/semidiscretization/semidiscretization_euler_acoustics.jl
  src/visualization/utilities.jl
  test/test_unit.jl
  utils/trixi2txt.jl
Labels: refactoring

#1901 Add preprocessing step to automate numbering in tutorial introduction
  docs/literate/make.jl
  docs/literate/src/files/index.jl
Labels: documentation

#1903 LinearizedEuler3D
  examples/p4est_3d_dgsem/elixir_linearizedeuler_convergence.jl
  examples/tree_3d_dgsem/elixir_linearizedeuler_gauss_wall.jl
  src/Trixi.jl
  src/equations/equations.jl
  src/equations/linearized_euler_1d.jl
  src/equations/linearized_euler_2d.jl
  src/equations/linearized_euler_3d.jl
  test/test_p4est_3d.jl
  test/test_tree_3d_linearizedeuler.jl
  test/test_tree_3d_part2.jl
  test/test_unit.jl
Labels: enhancement

#1911 Improve Docs for new Users
  docs/src/meshes/structured_mesh.md
  docs/src/meshes/tree_mesh.md
  docs/src/overview.md
Labels: documentation

#1892 First steps tutorial review procesing
  docs/literate/src/files/first_steps/changing_trixi.jl
  docs/literate/src/files/first_steps/create_first_setup.jl
  docs/literate/src/files/first_steps/getting_started.jl
  docs/make.jl
Labels: documentation

#1421 Unify `LaplaceDiffusion1D`, `LaplaceDiffusion2D`, and `LaplaceDiffusion3D` BCs
  src/equations/laplace_diffusion_1d.jl
  src/equations/laplace_diffusion_2d.jl
  src/equations/laplace_diffusion_3d.jl
Labels: refactoring

#1924 current filename for Unstructured/P4est
  src/meshes/mesh_io.jl
Labels: bug, consistency
