Repository trixi-framework/Trixi.jl, pull requests merged in 2024-05, with the labels that each got.

#1926 FluxChandrashekar_NormalDir
  src/equations/compressible_euler_2d.jl
  src/equations/compressible_euler_3d.jl
  test/test_p4est_2d.jl
  test/test_p4est_3d.jl
  test/test_unit.jl
Labels: enhancement

#1882 Add tutorial for subcell IDP limiting
  docs/literate/src/files/hohqmesh_tutorial.jl
  docs/literate/src/files/index.jl
  docs/literate/src/files/subcell_shock_capturing.jl
  docs/make.jl
Labels: documentation

#1940 Fix old API usage for Camera3D
  Project.toml
  docs/Project.toml
  ext/TrixiMakieExt.jl
  test/Project.toml
Labels: visualization, upstream

#1934 Add one-sided limiting for nonlinear variables to tutorial
  docs/literate/src/files/subcell_shock_capturing.jl
  src/equations/compressible_euler_2d.jl
Labels: documentation

#1938 Provide document of numeric types and type stability
  docs/src/conventions.md
Labels: documentation

#1945 Mean value in Zhang-Shu limiter on curved meshes
  src/callbacks_stage/positivity_zhang_shu_dg2d.jl
  src/callbacks_stage/positivity_zhang_shu_dg3d.jl
  src/solvers/dgsem_structured/dg.jl
  src/solvers/dgsem_tree/dg.jl
Labels: bug

#1908 Perk p2 single ext
  .github/workflows/Downgrade.yml
  NEWS.md
  Project.toml
  examples/tree_1d_dgsem/elixir_advection_perk2.jl
  ext/TrixiConvexECOSExt.jl
  src/Trixi.jl
  src/time_integration/paired_explicit_runge_kutta/methods_PERK2.jl
  src/time_integration/paired_explicit_runge_kutta/paired_explicit_runge_kutta.jl
  src/time_integration/paired_explicit_runge_kutta/polynomial_optimizer.jl
  src/time_integration/time_integration.jl
  test/Project.toml
  test/test_tree_1d_advection.jl
  test/test_trixi.jl
  test/test_unit.jl
Labels: enhancement

#1946 Add subcell limiting support for StructuredMesh
  NEWS.md
  examples/structured_2d_dgsem/elixir_euler_sedov_blast_wave_sc_subcell.jl
  src/callbacks_stage/subcell_bounds_check.jl
  src/callbacks_stage/subcell_bounds_check_2d.jl
  src/callbacks_stage/subcell_limiter_idp_correction_2d.jl
  src/solvers/dgsem_structured/dg.jl
  src/solvers/dgsem_structured/dg_2d_subcell_limiters.jl
  src/solvers/dgsem_structured/subcell_limiters_2d.jl
  src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
  src/solvers/dgsem_tree/subcell_limiters_2d.jl
  test/test_structured_2d.jl
Labels: enhancement

#1913 Read in capacity for parallel TreeMesh
  examples/tree_2d_dgsem/elixir_advection_restart_amr.jl
  src/meshes/mesh_io.jl
  test/test_mpi_tree.jl
Labels: bug, parallelization
