Repository trixi-framework/Trixi.jl, pull requests merged in 2024-01, with the labels that each got.

#1798 Fix boundary_condition_slip_wall for SWE
  examples/tree_2d_dgsem/elixir_shallowwater_wall.jl
  src/equations/shallow_water_2d.jl
  test/test_tree_2d_shallowwater.jl
Labels: bug

#1801 Fix link to download notebook badge in documentation
  docs/literate/make.jl
  docs/literate/src/files/index.jl
Labels: documentation

#1802 use julia-actions/cache also for Documenter
  .github/workflows/Documenter.yml
Labels: documentation, testing

#1799 Different Boundary Conditions for Standard Abaqus
  NEWS.md
  docs/literate/src/files/p4est_from_gmsh.jl
  docs/make.jl
  docs/src/meshes/p4est_mesh.md
  examples/p4est_2d_dgsem/elixir_euler_NACA6412airfoil_mach2.jl
  examples/p4est_3d_dgsem/elixir_euler_free_stream_boundaries.jl
  src/meshes/p4est_mesh.jl
  test/test_p4est_2d.jl
  test/test_p4est_3d.jl
Labels: enhancement

#1814 Fix Docs rendering: Avoid Markdown hyperlink
  docs/src/meshes/p4est_mesh.md
Labels: documentation

#1736 (Thread-)Parallelize bounds check routine for subcell IDP limiting
  src/callbacks_stage/subcell_bounds_check.jl
  src/callbacks_stage/subcell_bounds_check_2d.jl
  src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
  src/solvers/dgsem_tree/subcell_limiters_2d.jl
Labels: performance, parallelization

#1821 Remove race condition in mpi testing
  test/test_mpi.jl
  test/test_mpi_tree.jl
  test/test_threaded.jl
Labels: bug
