Repository trixi-framework/Trixi.jl, pull requests merged in 2025-02, with the labels that each got.

#2248 Time-dependent CFL
  NEWS.md
  examples/p4est_2d_dgsem/elixir_mhd_rotor_cfl_ramp.jl
  src/callbacks_step/glm_speed.jl
  src/callbacks_step/stepsize.jl
  src/semidiscretization/semidiscretization_coupled.jl
  test/test_p4est_2d.jl
  test/test_structured_2d.jl
Labels: enhancement

#2257 Check that `coordinates_min[dim] < coordinates_max[dim]`
  src/meshes/abstract_tree.jl
  src/meshes/p4est_mesh.jl
  src/meshes/structured_mesh.jl
  src/meshes/t8code_mesh.jl
  src/meshes/tree_mesh.jl
Labels: low-priority, refactoring

#2254 Remove coverage_override and use primary test run for code coverage
  .github/workflows/ci.yml
  test/runtests.jl
  test/test_mpi_p4est_2d.jl
  test/test_mpi_p4est_3d.jl
  test/test_mpi_t8code_2d.jl
  test/test_mpi_t8code_3d.jl
  test/test_mpi_tree.jl
  test/test_p4est_2d.jl
  test/test_p4est_3d.jl
  test/test_paper_self_gravitating_gas_dynamics.jl
  test/test_parabolic_1d.jl
  test/test_parabolic_2d.jl
  test/test_special_elixirs.jl
  test/test_structured_2d.jl
  test/test_structured_3d.jl
  test/test_t8code_2d.jl
  test/test_t8code_3d.jl
  test/test_threaded.jl
  test/test_tree_1d_advection.jl
  test/test_tree_1d_euler.jl
  test/test_tree_1d_mhd.jl
  test/test_tree_1d_mhdmulti.jl
  test/test_tree_1d_shallowwater.jl
  test/test_tree_2d_advection.jl
  test/test_tree_2d_euler.jl
  test/test_tree_2d_eulermulti.jl
  test/test_tree_2d_kpp.jl
  test/test_tree_2d_mhd.jl
  test/test_tree_3d_advection.jl
  test/test_tree_3d_euler.jl
  test/test_trixi.jl
  test/test_unstructured_2d.jl
Labels: testing

#2261 Always process code coverage
  .github/workflows/ci.yml
Labels: testing

#2250 Add support for plotting 1D function
  src/visualization/recipes_plots.jl
  src/visualization/types.jl
  src/visualization/utilities.jl
  test/test_visualization.jl
Labels: enhancement, visualization

#2258 Allow disabling reinterpolation in 1D plots
  src/visualization/recipes_plots.jl
  src/visualization/types.jl
  src/visualization/utilities.jl
  test/test_visualization.jl
Labels: enhancement, visualization

#2150 Use `VectorOfArray` in `wrap_array` for `DGMulti` solvers
  NEWS.md
  Project.toml
  docs/src/visualization.md
  examples/dgmulti_1d/elixir_euler_shu_osher_gauss_shock_capturing.jl
  src/Trixi.jl
  src/semidiscretization/semidiscretization.jl
  src/solvers/dgmulti/dg.jl
  src/solvers/dgmulti/flux_differencing_gauss_sbp.jl
  src/visualization/types.jl
  test/test_dgmulti_1d.jl
  test/test_dgmulti_2d.jl
  test/test_dgmulti_3d.jl
  test/test_parabolic_2d.jl
  test/test_parabolic_3d.jl
  test/test_threaded.jl
  test/test_visualization.jl
Labels: breaking

#2155 Print Analysis in Full Precision to File
  NEWS.md
  src/callbacks_step/analysis.jl
Labels: discussion, low-priority, breaking

#2200 Add flexibility to nonconservative BCs
  NEWS.md
  docs/literate/src/files/adding_nonconservative_equation.jl
  docs/literate/src/files/non_periodic_boundaries.jl
  examples/dgmulti_2d/elixir_mhd_reflective_wall.jl
  src/basic_types.jl
  src/equations/equations.jl
  src/equations/shallow_water_1d.jl
  src/equations/shallow_water_2d.jl
  src/solvers/dgmulti/dg.jl
  src/solvers/dgsem_p4est/dg_2d.jl
  src/solvers/dgsem_tree/dg_1d.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_unstructured/dg_2d.jl
  test/test_type.jl
Labels: enhancement, breaking, refactoring

#2267 speed-up parabolic CI
  test/test_parabolic_3d.jl
Labels: testing

#2268 speed-up DGMulti CI
  test/test_dgmulti_3d.jl
Labels: testing

#2271 fix plotting 1d function
  src/visualization/recipes_plots.jl
  src/visualization/types.jl
Labels: bug

#2269 Add test for non-conservative `boundary_condition_do_nothing`
  test/test_unit.jl
Labels: testing

#2277 Comments for custom TimeIntegrator fields
  src/time_integration/methods_2N.jl
  src/time_integration/methods_3Sstar.jl
  src/time_integration/methods_SSP.jl
Labels: documentation, low-priority

#2228 Fix Base.show StructuredMesh
  src/meshes/structured_mesh.jl
Labels: low-priority

#2280 add documentation for new 1D plotting functionalities
  docs/src/visualization.md
Labels: documentation

#2281 Warn if some boundaries are not equipped with a BC
  src/solvers/dgsem_unstructured/sort_boundary_conditions.jl
Labels: low-priority

#2278 Fix Documentation for PERK 2,3 schemes + Quality of Life Changes
  ext/TrixiConvexECOSExt.jl
  src/time_integration/paired_explicit_runge_kutta/methods_PERK2.jl
  src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
  src/time_integration/paired_explicit_runge_kutta/polynomial_optimizer.jl
Labels: documentation, refactoring

#2292 Use number of threads for performance indices
  NEWS.md
  docs/src/performance.md
  src/callbacks_step/analysis.jl
Labels: breaking

#2213 Implement collision source terms for multi-ion MHD
  examples/tree_2d_dgsem/elixir_mhdmultiion_collisions.jl
  src/Trixi.jl
  src/equations/ideal_glm_mhd_multiion.jl
  src/equations/ideal_glm_mhd_multiion_2d.jl
  test/test_tree_2d_mhdmultiion.jl
  test/test_type.jl
Labels: enhancement

#2299 Add information about specializing routines
  docs/literate/src/files/adding_nonconservative_equation.jl
Labels: documentation

#2297 Correct doc string for T8codeMeshCubedSphere
  examples/t8code_3d_dgsem/elixir_advection_cubed_sphere.jl
  src/meshes/t8code_mesh.jl
Labels: bug, documentation

#2291 Add Winters et al matrix dissipation for 1D, 2D Euler
  examples/dgmulti_1d/elixir_euler_modified_sod.jl
  src/Trixi.jl
  src/equations/compressible_euler_1d.jl
  src/equations/compressible_euler_2d.jl
  src/equations/compressible_euler_3d.jl
  src/equations/numerical_fluxes.jl
  test/test_dgmulti_1d.jl
  test/test_p4est_3d.jl
  test/test_tree_2d_euler.jl
  test/test_unit.jl
Labels: enhancement
