Repository trixi-framework/Trixi.jl, pull requests merged in 2025-08, with the labels that each got.

#2510 Refactor custom SSPRK code to be consistent
  src/time_integration/methods_SSP.jl
  src/time_integration/time_integration.jl
Labels: refactoring

#2509 Remove redundant `function solve(` for relaxation integrators
  src/time_integration/relaxation_methods/methods_subdiagonal.jl
  src/time_integration/relaxation_methods/methods_vanderHouwen.jl
  src/time_integration/relaxation_methods/relaxation_methods.jl
Labels: refactoring, merge me

#2516 `return nothing` where nothing is returned
  src/callbacks_stage/entropy_bounded_limiter.jl
  src/callbacks_stage/positivity_zhang_shu.jl
  src/callbacks_step/amr_dg.jl
  src/callbacks_step/amr_dg1d.jl
  src/callbacks_step/amr_dg2d.jl
  src/callbacks_step/callbacks_step.jl
  src/callbacks_step/save_solution.jl
  src/callbacks_step/time_series_dg_tree.jl
  src/callbacks_step/time_series_dg_unstructured.jl
  src/meshes/structured_mesh_view.jl
  src/semidiscretization/semidiscretization_coupled.jl
  src/solvers/dg.jl
  src/solvers/dgmulti/dg.jl
  src/solvers/dgmulti/dg_parabolic.jl
  src/solvers/dgmulti/shock_capturing.jl
  src/solvers/dgsem_p4est/dg_2d.jl
  src/solvers/dgsem_p4est/dg_2d_parabolic.jl
  src/solvers/dgsem_p4est/dg_2d_parallel.jl
  src/solvers/dgsem_p4est/dg_3d.jl
  src/solvers/dgsem_p4est/dg_3d_parabolic.jl
  src/solvers/dgsem_p4est/dg_3d_parallel.jl
  src/solvers/dgsem_structured/containers.jl
  src/solvers/dgsem_structured/containers_1d.jl
  src/solvers/dgsem_structured/containers_2d.jl
  src/solvers/dgsem_structured/containers_3d.jl
  src/solvers/dgsem_structured/dg.jl
  src/solvers/dgsem_structured/dg_1d.jl
  src/solvers/dgsem_structured/dg_2d.jl
  src/solvers/dgsem_structured/dg_3d.jl
  src/solvers/dgsem_structured/indicators_1d.jl
  src/solvers/dgsem_structured/indicators_2d.jl
  src/solvers/dgsem_structured/indicators_3d.jl
  src/solvers/dgsem_tree/containers.jl
  src/solvers/dgsem_tree/dg.jl
  src/solvers/dgsem_tree/dg_1d.jl
  src/solvers/dgsem_tree/dg_1d_parabolic.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_tree/dg_2d_parabolic.jl
  src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
  src/solvers/dgsem_tree/dg_3d.jl
  src/solvers/dgsem_tree/dg_3d_parabolic.jl
  src/solvers/dgsem_tree/indicators_1d.jl
  src/solvers/dgsem_tree/indicators_2d.jl
  src/solvers/dgsem_tree/indicators_3d.jl
  src/solvers/dgsem_tree/subcell_limiters_2d.jl
  src/solvers/dgsem_unstructured/dg_2d.jl
  src/solvers/dgsem_unstructured/indicators_2d.jl
Labels: low-priority, refactoring, merge me

#2519 Mention Solver Source Code Logic in Docs
  docs/src/conventions.md
  src/solvers/dg.jl
Labels: documentation, merge me

#2520 Correct dispatch for `create_cache` of mortars
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_tree/dg_3d.jl
Labels: bug

#2517 `return nothing` & helper functions for custom time integrators
  src/time_integration/methods_2N.jl
  src/time_integration/methods_3Sstar.jl
  src/time_integration/methods_SSP.jl
  src/time_integration/paired_explicit_runge_kutta/methods_PERK2.jl
  src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
  src/time_integration/paired_explicit_runge_kutta/methods_PERK4.jl
  src/time_integration/paired_explicit_runge_kutta/paired_explicit_runge_kutta.jl
  src/time_integration/relaxation_methods/methods_subdiagonal.jl
  src/time_integration/relaxation_methods/methods_vanderHouwen.jl
  src/time_integration/relaxation_methods/relaxation_methods.jl
  src/time_integration/time_integration.jl
Labels: low-priority, refactoring

#2526 Rename elixir_euler_OMNERA_M6_wing.jl to elixir_euler_ONERA_M6_wing.jl
  examples/p4est_3d_dgsem/elixir_euler_ONERA_M6_wing.jl
  test/test_p4est_3d.jl
Labels: example

#2461 Specialize `SubcellLimiterIDP` for certain equations
  src/callbacks_stage/subcell_limiter_idp_correction.jl
  src/solvers/dgsem_p4est/subcell_limiters_2d.jl
  src/solvers/dgsem_structured/subcell_limiters_2d.jl
  src/solvers/dgsem_tree/subcell_limiters_2d.jl
Labels: enhancement

#2533 Debug `P4estElementContainer`
  src/solvers/dgsem_p4est/containers.jl
  src/solvers/dgsem_structured/containers.jl
  src/solvers/dgsem_unstructured/containers_2d.jl
Labels: bug, high-priority

#2535 Make `max_dt` more efficient for `constant_speed::True`
  src/callbacks_step/stepsize_dg1d.jl
  src/callbacks_step/stepsize_dg2d.jl
  src/callbacks_step/stepsize_dg3d.jl
  src/solvers/dgmulti/dg.jl
Labels: performance, refactoring, merge me
