Repository trixi-framework/Trixi.jl, pull requests merged in 2025-09, with the labels that each got.

#2505 Use Jacobian-free Newton-Krylov for SDIRK time integrators
  examples/p4est_2d_dgsem/elixir_navierstokes_viscous_shock_newton_krylov.jl
  examples/tree_1d_dgsem/elixir_diffusion_ldg.jl
  examples/tree_1d_dgsem/elixir_diffusion_ldg_newton_krylov.jl
  test/Project.toml
  test/test_parabolic_1d.jl
  test/test_parabolic_2d.jl
Labels: example

#2532 Jacobian sparsity pattern via `SparseConnectivityTracer` and `SparseMatrixColorings`
  Project.toml
  README.md
  docs/Project.toml
  docs/literate/src/files/differentiable_programming.jl
  docs/src/index.md
  examples/structured_2d_dgsem/elixir_euler_convergence_implicit_sparse_jacobian.jl
  examples/tree_2d_dgsem/elixir_advection_implicit_sparse_jacobian.jl
  examples/tree_2d_dgsem/elixir_advection_implicit_sparse_jacobian_restart.jl
  ext/TrixiSparseConnectivityTracerExt.jl
  src/semidiscretization/semidiscretization.jl
  test/Project.toml
  test/test_structured_2d.jl
  test/test_tree_2d_advection.jl
  test/test_unit.jl
Labels: enhancement

#2541 Single out `u_mean` computation into function
  src/callbacks_stage/entropy_bounded_limiter_1d.jl
  src/callbacks_stage/entropy_bounded_limiter_2d.jl
  src/callbacks_stage/entropy_bounded_limiter_3d.jl
  src/callbacks_stage/positivity_zhang_shu_dg1d.jl
  src/callbacks_stage/positivity_zhang_shu_dg2d.jl
  src/callbacks_stage/positivity_zhang_shu_dg3d.jl
  src/meshes/tree_mesh.jl
  src/solvers/dgsem/dgsem.jl
Labels: refactoring

#2551 Small cleanup of `flux_kennedy_gruber`
  src/equations/compressible_euler_3d.jl
Labels: low-priority, refactoring

#2558 Yet another docu formatting
  docs/literate/src/files/differentiable_programming.jl
  docs/src/time_integration.md
Labels: documentation

#2557 Finally fix code blocks in list 🤞
  docs/src/heterogeneous.md
Labels: documentation

#2562 Clarify `direction` instead of `normal_direction` for `TreeMesh` BCs
  examples/tree_1d_dgsem/elixir_burgers_rarefaction.jl
  examples/tree_1d_dgsem/elixir_burgers_shock.jl
  examples/tree_1d_dgsem/elixir_navierstokes_viscous_shock.jl
  examples/tree_1d_dgsem/elixir_traffic_flow_lwr_trafficjam.jl
  examples/tree_2d_dgsem/elixir_euler_subsonic_constant.jl
Labels: example

#2561 Schulz-Rinne (2D) Riemann Problem
  examples/tree_2d_dgsem/elixir_euler_riemannproblem_quadrants_amr.jl
  test/test_tree_2d_euler.jl
Labels: example

#2554 `PlotData2D` for coupled semidiscretization
  src/visualization/types.jl
  test/test_structured_2d.jl
Labels: enhancement, visualization

#2574 Elixir with constant subsonic state and boundary treatment
  examples/p4est_2d_dgsem/elixir_euler_subsonic_constant.jl
  test/test_p4est_2d.jl
  test/test_tree_2d_euler.jl
Labels: example

#2573 Refactor dimension-(in)dependent implementation of subcell limiting
  src/solvers/dgsem_tree/subcell_limiters.jl
  src/solvers/dgsem_tree/subcell_limiters_2d.jl
Labels: refactoring

#2581 Fix allocations when (subcell) limit multiple nonlinear variables
  src/solvers/dgsem_tree/subcell_limiters.jl
  src/solvers/dgsem_tree/subcell_limiters_2d.jl
Labels: bug, performance

#2566 Use `Base.max` in computation of time step to prevent silent failures
  src/callbacks_step/stepsize_dg1d.jl
  src/callbacks_step/stepsize_dg2d.jl
  src/callbacks_step/stepsize_dg3d.jl
Labels: bug, refactoring

#2584 Fix Docstring P4estCubedSphere
  examples/p4est_3d_dgsem/elixir_advection_cubed_sphere.jl
  examples/p4est_3d_dgsem/elixir_euler_baroclinic_instability.jl
  examples/p4est_3d_dgsem/elixir_euler_circular_wind_nonconforming.jl
  examples/p4est_3d_dgsem/elixir_euler_source_terms_nonconforming_earth.jl
  src/meshes/p4est_mesh.jl
  src/meshes/t8code_mesh.jl
Labels: documentation

#2589 Don't reset entries of `antidiffusive_flux` every `rhs!`
  src/solvers/dgsem_tree/containers_2d.jl
  src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
Labels: performance, refactoring

#2400 Use variable name `have_nonconservative_terms` everywhere
  src/semidiscretization/semidiscretization_coupled.jl
  src/solvers/dgmulti/flux_differencing.jl
  src/solvers/dgmulti/sbp.jl
  src/solvers/dgsem_p4est/dg_2d.jl
  src/solvers/dgsem_p4est/dg_2d_parabolic.jl
  src/solvers/dgsem_p4est/dg_2d_parallel.jl
  src/solvers/dgsem_p4est/dg_3d.jl
  src/solvers/dgsem_p4est/dg_3d_parabolic.jl
  src/solvers/dgsem_p4est/dg_3d_parallel.jl
  src/solvers/dgsem_structured/dg.jl
  src/solvers/dgsem_structured/dg_2d.jl
  src/solvers/dgsem_structured/dg_2d_compressible_euler.jl
  src/solvers/dgsem_structured/dg_2d_subcell_limiters.jl
  src/solvers/dgsem_structured/dg_3d.jl
  src/solvers/dgsem_structured/dg_3d_compressible_euler.jl
  src/solvers/dgsem_tree/dg_1d.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_tree/dg_2d_compressible_euler.jl
  src/solvers/dgsem_tree/dg_2d_parallel.jl
  src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
  src/solvers/dgsem_tree/dg_3d.jl
  src/solvers/dgsem_tree/dg_3d_compressible_euler.jl
  src/solvers/dgsem_unstructured/dg_2d.jl
  src/solvers/fdsbp_tree/fdsbp.jl
  src/solvers/fdsbp_tree/fdsbp_1d.jl
  src/solvers/fdsbp_tree/fdsbp_2d.jl
  src/solvers/fdsbp_tree/fdsbp_3d.jl
  src/solvers/fdsbp_unstructured/fdsbp_2d.jl
  test/test_performance_specializations_2d.jl
  test/test_performance_specializations_3d.jl
Labels: discussion, consistency, refactoring
