Repository trixi-framework/Trixi.jl, pull requests merged in 2025-03, with the labels that each got.

#2303 -pre -> -DEV for version numbers
  docs/src/development.md
Labels: documentation

#2304 Finalize callbacks for custom time integrators
  src/time_integration/methods_2N.jl
  src/time_integration/methods_3Sstar.jl
  src/time_integration/methods_SSP.jl
  src/time_integration/paired_explicit_runge_kutta/paired_explicit_runge_kutta.jl
  src/time_integration/time_integration.jl
Labels: bug

#2147 PERK4 standalone
  NEWS.md
  docs/src/time_integration.md
  examples/structured_2d_dgsem/elixir_euler_vortex_perk4.jl
  examples/tree_1d_dgsem/elixir_hypdiff_nonperiodic_perk4.jl
  ext/TrixiConvexECOSExt.jl
  src/time_integration/paired_explicit_runge_kutta/methods_PERK4.jl
  src/time_integration/paired_explicit_runge_kutta/paired_explicit_runge_kutta.jl
  test/test_structured_2d.jl
  test/test_tree_1d_hypdiff.jl
  test/test_unit.jl
Labels: enhancement

#2309 fix IndicatorLöhner on ARM with multiple threads
  src/solvers/dgsem_tree/indicators_1d.jl
  src/solvers/dgsem_tree/indicators_2d.jl
  src/solvers/dgsem_tree/indicators_3d.jl
  test/test_threaded.jl
Labels: bug, parallelization

#2312 add docstrings for `density`, `pressure`, and `density_pressure`
  src/equations/equations.jl
Labels: documentation

#2313 improve performance of `unstructured_2d_to_1d_curve`
  src/meshes/abstract_tree.jl
  src/visualization/utilities.jl
Labels: visualization

#2314 Refactoring some `DGMulti` parabolic code
  src/solvers/dgmulti/dg_parabolic.jl
  test/test_parabolic_2d.jl
Labels: refactoring

#2315 Refactoring some `TreeMesh` parabolic code
  src/solvers/dgsem_tree/dg_1d_parabolic.jl
  src/solvers/dgsem_tree/dg_2d_parabolic.jl
  src/solvers/dgsem_tree/dg_3d_parabolic.jl
Labels: refactoring

#2319 Refactor Gradient Interfaces 3D TreeMesh
  src/solvers/dgsem_tree/dg_3d_parabolic.jl
Labels: refactoring

#2323 do not hardcode LoopVectorization.jl version in checks for warnings for high-precision floats
  test/test_trixi.jl
Labels: testing

#2328 HDF5 library install procedure
  docs/src/parallelization.md
Labels: documentation

#2330 improve performance of `unstructured_3d_to_1d_curve` for the `P4estMesh`
  src/visualization/types.jl
  src/visualization/utilities.jl
  test/test_visualization.jl
Labels: performance, visualization

#2318 improve performance of `unstructured_3d_to_1d_curve`
  src/visualization/utilities.jl
Labels: performance, visualization

#2336 move `get_unstructured_data` where it is used
  src/visualization/types.jl
Labels: performance, visualization

#2331 Broadcast p4est mesh data across MPI for Abaqus inp meshes
  src/meshes/p4est_mesh.jl
  test/test_mpi_p4est_2d.jl
  test/test_p4est_2d.jl
Labels: bug, enhancement

#2337 improve performance of `unstructured_3d_to_1d_curve` for linear `P4estMesh`es in 3D
  src/visualization/utilities_p4est_t8code.jl
  test/test_visualization.jl
Labels: performance, visualization

#2334 improve performance of `unstructured_3d_to_1d_curve` for linear `P4estMesh`es and `T8codeMesh`es in 3D
  src/auxiliary/p4est.jl
  src/visualization/types.jl
  src/visualization/utilities.jl
  src/visualization/utilities_p4est_t8code.jl
  src/visualization/visualization.jl
  test/test_visualization.jl
Labels: performance, visualization

#2326 improve performance of `unstructured_2d_to_1d_curve`
  src/visualization/utilities.jl
Labels: performance, visualization
