Repository trixi-framework/Trixi.jl, pull requests merged in 2025-05, with the labels that each got.

#2381 `sincospi`
  src/equations/compressible_euler_2d.jl
  src/equations/compressible_euler_3d.jl
  src/equations/compressible_euler_quasi_1d.jl
  src/equations/hyperbolic_diffusion_2d.jl
  src/equations/ideal_glm_mhd_1d.jl
  src/equations/ideal_glm_mhd_multicomponent_1d.jl
  src/solvers/dgsem/basis_lobatto_legendre.jl
Labels: low-priority, refactoring

#2380 fix links to new docs repo
  .github/review-checklist.md
  README.md
  benchmark/README.md
  docs/literate/src/files/adding_nonconservative_equation.jl
  docs/literate/src/files/custom_semidiscretization.jl
  docs/literate/src/files/first_steps/create_first_setup.jl
  docs/literate/src/files/hohqmesh_tutorial.jl
  docs/src/development.md
  docs/src/index.md
  docs/src/meshes/structured_mesh.md
  docs/src/overview.md
  docs/src/parallelization.md
  docs/src/time_integration.md
  examples/p4est_3d_dgsem/elixir_linearizedeuler_convergence.jl
  src/auxiliary/p4est.jl
  src/auxiliary/t8code.jl
Labels: documentation

#2389 Add `@ref`s for Navier-Stokes-Boundary `struct`s
  src/equations/compressible_euler_2d.jl
  src/equations/compressible_euler_3d.jl
  src/equations/compressible_navier_stokes.jl
Labels: documentation, low-priority

#2391 add docstring to `IndicatorLoehner`
  src/solvers/dgsem_tree/indicators.jl
Labels: documentation

#2397 Make line breaks more consistent/semantic
  src/solvers/dgsem_p4est/dg_2d.jl
  src/solvers/dgsem_p4est/dg_2d_parabolic.jl
  src/solvers/dgsem_p4est/dg_2d_parallel.jl
  src/solvers/dgsem_p4est/dg_3d.jl
  src/solvers/dgsem_p4est/dg_3d_parabolic.jl
  src/solvers/dgsem_p4est/dg_3d_parallel.jl
  src/solvers/dgsem_structured/dg_2d.jl
  src/solvers/dgsem_structured/dg_3d.jl
  src/solvers/dgsem_tree/dg_1d.jl
  src/solvers/dgsem_tree/dg_1d_parabolic.jl
  src/solvers/dgsem_tree/dg_2d_parabolic.jl
  src/solvers/dgsem_tree/dg_3d.jl
  src/solvers/dgsem_tree/dg_3d_parabolic.jl
  src/solvers/dgsem_unstructured/dg_2d.jl
Labels: discussion, low-priority, refactoring

#2388 Use `reinterpret` when applying `solution_variables` for visualization
  src/visualization/utilities.jl
Labels: documentation, low-priority

#2402 Make Convergence Test MHD Docstrings more helpful
  src/equations/ideal_glm_mhd_1d.jl
  src/equations/ideal_glm_mhd_2d.jl
  src/equations/ideal_glm_mhd_3d.jl
Labels: documentation, low-priority

#2403 Recommend using TestPicker.jl in docs
  docs/src/testing.md
Labels: documentation, testing

#2407 Move tutorial notebooks hosting to TrixiDocumentation
  .github/workflows/CacheNotebooks.yml
  docs/literate/make.jl
Labels: documentation

#2408 Restrict Polyester.jl to v0.7.16
  Project.toml
Labels: bug, testing, parallelization, upstream

#2413 Correct comments on code location
  src/equations/compressible_euler_2d.jl
  src/equations/compressible_euler_3d.jl
Labels: documentation, low-priority

#2418 Docstring Enstrophy, Export+Docstring Vorticity
  src/Trixi.jl
  src/equations/compressible_navier_stokes_2d.jl
  src/equations/compressible_navier_stokes_3d.jl
Labels: documentation

#2406 Add Laplace diffusion in terms of entropy variables
  NEWS.md
  examples/dgmulti_2d/elixir_euler_laplace_diffusion.jl
  examples/tree_1d_dgsem/elixir_euler_laplace_diffusion.jl
  examples/tree_3d_dgsem/elixir_euler_laplace_diffusion.jl
  src/Trixi.jl
  src/equations/equations_parabolic.jl
  src/equations/laplace_diffusion_entropy_variables.jl
  src/equations/laplace_diffusion_entropy_variables_1d.jl
  src/equations/laplace_diffusion_entropy_variables_2d.jl
  src/equations/laplace_diffusion_entropy_variables_3d.jl
  test/test_dgmulti_2d.jl
  test/test_tree_1d_euler.jl
  test/test_tree_3d_euler.jl
Labels: enhancement

#2416 Symmetry/Slip-Wall boundary condition for Navier-Stokes
  NEWS.md
  examples/p4est_2d_dgsem/elixir_navierstokes_blast_reflective.jl
  examples/p4est_2d_dgsem/elixir_navierstokes_freestream_symmetry.jl
  examples/p4est_3d_dgsem/elixir_navierstokes_crm.jl
  src/Trixi.jl
  src/equations/compressible_navier_stokes.jl
  src/equations/compressible_navier_stokes_2d.jl
  src/equations/compressible_navier_stokes_3d.jl
  src/solvers/dgsem_tree/dg_2d_parabolic.jl
  src/solvers/dgsem_tree/dg_3d_parabolic.jl
  test/test_parabolic_2d.jl
  test/test_parabolic_3d.jl
Labels: enhancement, discussion
