Repository trixi-framework/Trixi.jl, pull requests merged in 2025-01, with the labels that each got.

#2218 Format & Comment custom integrators
  src/semidiscretization/semidiscretization_euler_gravity.jl
  src/time_integration/methods_2N.jl
  src/time_integration/methods_3Sstar.jl
Labels: low-priority, refactoring

#2223 Explain parameters of `ParametersEulerGravity`
  src/Trixi.jl
  src/semidiscretization/semidiscretization_euler_gravity.jl
Labels: documentation, low-priority

#2219 Docstrings for `flux_godunov` and `flux_ec`
  src/equations/hyperbolic_diffusion_2d.jl
  src/equations/hyperbolic_diffusion_3d.jl
  src/equations/inviscid_burgers_1d.jl
  src/equations/lattice_boltzmann_2d.jl
  src/equations/lattice_boltzmann_3d.jl
  src/equations/linear_scalar_advection_1d.jl
  src/equations/linear_scalar_advection_2d.jl
  src/equations/linear_scalar_advection_3d.jl
Labels: documentation, low-priority

#2217 Second-order Quadrilaterals (2D) meshes in standard Abaqus `.inp` format
  NEWS.md
  docs/literate/src/files/p4est_from_gmsh.jl
  docs/src/meshes/p4est_mesh.md
  examples/p4est_2d_dgsem/elixir_euler_free_stream_hybrid_mesh.jl
  examples/p4est_2d_dgsem/elixir_navierstokes_SD7003airfoil.jl
  src/meshes/p4est_mesh.jl
  src/meshes/t8code_mesh.jl
  test/test_p4est_2d.jl
  test/test_parabolic_2d.jl
Labels: enhancement

#2227 Correct Formula for Potential Energy
  examples/paper_self_gravitating_gas_dynamics/elixir_eulergravity_jeans_instability.jl
Labels: bug

#2224 `resize!` only when needed `EulerGravity`
  src/semidiscretization/semidiscretization_euler_gravity.jl
Labels: performance, refactoring

#2231 Tidy up comments LBM
  src/equations/lattice_boltzmann_2d.jl
  src/equations/lattice_boltzmann_3d.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_tree/dg_2d_parabolic.jl
Labels: low-priority, refactoring

#2238 Update comments for some `DGSEM` APIs
  src/solvers/dgsem/dgsem.jl
Labels: documentation

#2245 Correct Link to published version for Euler Blob resource
  examples/tree_2d_dgsem/elixir_euler_blob_amr.jl
  examples/tree_2d_dgsem/elixir_euler_blob_mortar.jl
  examples/tree_3d_dgsem/elixir_euler_blob_amr.jl
Labels: low-priority

#2247 Dirichlet BC for 3D Navier-Stokes
  examples/p4est_3d_dgsem/elixir_navierstokes_viscous_shock_dirichlet_bc.jl
  src/equations/compressible_navier_stokes_1d.jl
  src/equations/compressible_navier_stokes_2d.jl
  src/equations/compressible_navier_stokes_3d.jl
  test/test_parabolic_3d.jl
Labels: enhancement

#2246 von-Karman Vortex Street
  examples/p4est_2d_dgsem/elixir_navierstokes_vortex_street.jl
  test/test_parabolic_2d.jl
Labels: enhancement
