Repository trixi-framework/Trixi.jl, pull requests merged in 2025-04, with the labels that each got.

#2340 improve performance of `unstructured_2d_to_1d_curve` for linear `P4estMesh`es in 2D
  src/visualization/types.jl
  src/visualization/utilities.jl
  src/visualization/utilities_p4est_t8code.jl
  test/test_visualization.jl
Labels: performance, visualization

#2333 Add `ViscousFormulationLDG` support to `TreeMesh`
  examples/tree_1d_dgsem/elixir_advection_diffusion_ldg.jl
  examples/tree_1d_dgsem/elixir_diffusion_ldg.jl
  examples/tree_2d_dgsem/elixir_advection_diffusion.jl
  examples/tree_2d_dgsem/elixir_advection_diffusion_nonperiodic.jl
  examples/tree_3d_dgsem/elixir_advection_diffusion_nonperiodic.jl
  src/solvers/dgmulti/dg_parabolic.jl
  src/solvers/dgsem_tree/dg_1d_parabolic.jl
  src/solvers/dgsem_tree/dg_2d_parabolic.jl
  src/solvers/dgsem_tree/dg_3d_parabolic.jl
  src/solvers/solvers_parabolic.jl
  test/test_parabolic_1d.jl
  test/test_parabolic_2d.jl
  test/test_parabolic_3d.jl
Labels: enhancement

#2344 Enhanced Docstring BR1; Mention LDG in diffusion-dominated testcase
  examples/tree_1d_dgsem/elixir_navierstokes_viscous_shock.jl
  src/solvers/solvers_parabolic.jl
Labels: documentation

#2342 Add Interval option for `StepsizeCallback`
  src/callbacks_step/stepsize.jl
  test/test_parabolic_2d.jl
Labels: enhancement, performance

#2352 document and export `waterheight` and `waterheight_pressure`
  src/Trixi.jl
  src/equations/equations.jl
Labels: documentation

#2356 Update parallelization.md: Mention issues with `MPIPreferences`
  docs/src/parallelization.md
Labels: documentation

#2347 Document `p4est` interfacing
  docs/src/meshes/p4est_mesh.md
Labels: documentation

#2362 Remove `P4estMesh{1}`
  src/solvers/dgsem_tree/dg_1d.jl
  src/solvers/dgsem_tree/indicators_1d.jl
Labels: refactoring

#2360 Fix vortex street elixir
  examples/p4est_2d_dgsem/elixir_navierstokes_vortex_street.jl
  test/test_parabolic_2d.jl
Labels: bug

#2110 WIP: Sc/Enhanced p4est mesh views
  examples/p4est_2d_dgsem/elixir_advection_meshview.jl
  src/Trixi.jl
  src/callbacks_step/analysis_dg2d.jl
  src/callbacks_step/save_solution_dg.jl
  src/callbacks_step/stepsize_dg2d.jl
  src/meshes/mesh_io.jl
  src/meshes/meshes.jl
  src/meshes/p4est_mesh_view.jl
  src/semidiscretization/semidiscretization_hyperbolic.jl
  src/solvers/dg.jl
  src/solvers/dgsem_p4est/containers.jl
  src/solvers/dgsem_p4est/containers_2d.jl
  src/solvers/dgsem_p4est/dg.jl
  src/solvers/dgsem_p4est/dg_2d.jl
  src/solvers/dgsem_p4est/dg_2d_parabolic.jl
  src/solvers/dgsem_structured/dg_2d.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_unstructured/dg_2d.jl
  test/test_p4est_2d.jl
Labels: enhancement

#2285 Unify `create_cache` for `ControllerThreeLevel*` and the different mesh types
  examples/p4est_3d_dgsem/elixir_euler_weak_blast_wave_amr.jl
  src/callbacks_step/amr_dg.jl
  src/callbacks_step/amr_dg1d.jl
  src/callbacks_step/amr_dg2d.jl
  src/callbacks_step/amr_dg3d.jl
  test/test_p4est_3d.jl
Labels: refactoring

#2373 Use actual `Set` for nodesets, threaded BC association
  src/meshes/p4est_mesh.jl
Labels: refactoring

#2374 Use linear extrapolation in `cell2node` function
  src/visualization/utilities.jl
Labels: bug, visualization

#2364 Add passive tracers
  NEWS.md
  examples/p4est_2d_dgsem/elixir_euler_density_wave_tracers.jl
  examples/tree_1d_dgsem/elixir_euler_density_wave_tracers.jl
  examples/tree_2d_dgsem/elixir_euler_density_wave_tracers.jl
  src/Trixi.jl
  src/equations/compressible_euler_1d.jl
  src/equations/equations.jl
  src/equations/passive_tracers.jl
  test/test_p4est_2d.jl
  test/test_tree_1d.jl
  test/test_tree_1d_passive_tracers.jl
  test/test_tree_2d_part2.jl
  test/test_tree_2d_passive_tracers.jl
  test/test_type.jl
  test/test_unit.jl
Labels: enhancement

#2372 structured mesh with nonconservative fluxes
  examples/structured_2d_dgsem/elixir_mhd_onion.jl
  src/semidiscretization/semidiscretization_coupled.jl
  src/solvers/dgsem_structured/dg.jl
  src/solvers/dgsem_structured/dg_2d.jl
  src/solvers/dgsem_structured/dg_3d.jl
  test/test_structured_2d.jl
Labels: bug, enhancement

#2378 Remove `Alg` for `PERK` integrators
  src/time_integration/paired_explicit_runge_kutta/methods_PERK2.jl
  src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
  src/time_integration/paired_explicit_runge_kutta/methods_PERK4.jl
Labels: low-priority, refactoring

#2376 Deploy docs to trixi-framework/TrixiDocumentation
  .github/workflows/DocPreviewCleanup.yml
  .github/workflows/Documenter.yml
  docs/make.jl
Labels: documentation

#2375 Refactor `SurfaceIntegral` to make it 3D ready
  NEWS.md
  examples/p4est_2d_dgsem/elixir_euler_NACA0012airfoil_mach085.jl
  examples/p4est_2d_dgsem/elixir_euler_subsonic_cylinder.jl
  examples/p4est_2d_dgsem/elixir_navierstokes_NACA0012airfoil_mach08.jl
  examples/p4est_2d_dgsem/elixir_navierstokes_SD7003airfoil.jl
  src/Trixi.jl
  src/callbacks_step/analysis.jl
  src/callbacks_step/analysis_surface_integral.jl
  src/callbacks_step/analysis_surface_integral_2d.jl
Labels: refactoring
