Repository trixi-framework/Trixi.jl, pull requests merged in 2025-06, with the labels that each got.

#2234 CI: Split Parabolic
  .github/workflows/Downgrade.yml
  .github/workflows/ci.yml
  test/runtests.jl
Labels: discussion, testing

#2428 allow Polyester.jl v0.7.18
  Project.toml
Labels: upstream

#2434 Remove `SurfaceIntegral` from `prolong2interfaces` (no dispatch implemented)
  src/solvers/dgmulti/dg.jl
  src/solvers/dgmulti/flux_differencing.jl
  src/solvers/dgmulti/sbp.jl
  src/solvers/dgsem_p4est/dg_2d.jl
  src/solvers/dgsem_p4est/dg_2d_parabolic.jl
  src/solvers/dgsem_p4est/dg_3d.jl
  src/solvers/dgsem_p4est/dg_3d_parabolic.jl
  src/solvers/dgsem_p4est/dg_3d_parallel.jl
  src/solvers/dgsem_tree/dg_1d.jl
  src/solvers/dgsem_tree/dg_1d_parabolic.jl
  src/solvers/dgsem_tree/dg_2d.jl
  src/solvers/dgsem_tree/dg_2d_parabolic.jl
  src/solvers/dgsem_tree/dg_2d_parallel.jl
  src/solvers/dgsem_tree/dg_3d.jl
  src/solvers/dgsem_tree/dg_3d_parabolic.jl
  src/solvers/dgsem_unstructured/dg_2d.jl
Labels: low-priority, refactoring, merge me

#2440 Add parameter `mesh` to `get_boundary_outer_state` for subcell limiting
  examples/p4est_2d_dgsem/elixir_euler_supersonic_cylinder_sc_subcell.jl
  src/solvers/dgsem_p4est/subcell_limiters_2d.jl
  src/solvers/dgsem_structured/subcell_limiters_2d.jl
  src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
  src/solvers/dgsem_tree/subcell_limiters_2d.jl
Labels: low-priority

#2426 3D Lift & Drag Pressure-based Coefficients
  examples/p4est_3d_dgsem/elixir_euler_OMNERA_M6_wing.jl
  src/Trixi.jl
  src/callbacks_step/analysis_surface_integral.jl
  src/callbacks_step/analysis_surface_integral_2d.jl
  src/callbacks_step/analysis_surface_integral_3d.jl
  test/test_p4est_3d.jl
Labels: enhancement, example

#2429 Subcell-limiting for nonconservative terms in "local * jump" form
  NEWS.md
  src/Trixi.jl
  src/equations/equations.jl
  src/equations/ideal_glm_mhd_2d.jl
  src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
  test/test_tree_2d_mhd.jl
Labels: enhancement

#2454 Fix docstring `flux_parabolic`
  src/solvers/solvers_parabolic.jl
Labels: documentation

#2452 Example for restarting hyperbolic-parabolic from purely hyperbolic
  examples/p4est_2d_dgsem/elixir_euler_NACA0012airfoil_mach085.jl
  examples/p4est_2d_dgsem/elixir_navierstokes_NACA0012airfoil_mach085_restart.jl
  test/test_parabolic_2d.jl
Labels: low-priority, example

#2419 Couette + Poiseuille flow
  examples/p4est_2d_dgsem/elixir_navierstokes_couette_flow.jl
  examples/p4est_2d_dgsem/elixir_navierstokes_poiseuille_flow.jl
  test/test_parabolic_2d.jl
Labels: low-priority, example

#2441 Fix bug in Dirichlet BC for non-conservative equations
  examples/tree_2d_dgsem/elixir_mhd_alfven_wave_dirichlet.jl
  src/equations/equations.jl
  src/equations/ideal_glm_mhd_1d.jl
  src/equations/ideal_glm_mhd_2d.jl
  test/test_mpi_p4est_2d.jl
  test/test_p4est_2d.jl
  test/test_structured_2d.jl
  test/test_tree_2d_mhd.jl
  test/test_unstructured_2d.jl
Labels: bug
